### ISSUE TITLE
Refernece Designator for TL431DBZ

### ISSUE THREAD

**Issue by leoheck** [KiCad/kicad-symbols#1004]
I believe that the reference designator for the `Reference_Voltage:TL431DBZ` should be `U` because it is an IC. Right know it has the diode `D` designator.

**Comment by evanshultz** [comment]
This goes for all symbols in this library with a D refdes prefix now:
- CJ432
- LM285*
- LM403*
- LM404*
- TL43*

**Comment by antoniovazquezblanco** [comment]
PR with fix sent in https://github.com/KiCad/kicad-symbols/pull/1220
