### ISSUE TITLE
Will the RT8462 model and the XHP35A-01-0000-0D0HC40E7DKR-ND component model?

### ISSUE THREAD

**Issue by jyun0213** [KiCad/kicad-symbols#1063]
Will the RT8462 model and the XHP35A-01-0000-0D0HC40E7DKR-ND component model?
Can you teach how to set it up?

**Comment by poeschlr** [comment]
You created this as an issue on the symbol library repo. These things are normally reserved for bug reports. If you need help understanding some kicad functionality then you might want to head over to the forum https://forum.kicad.info/
I would also suggest you add more information once you create your question over there.
