### ISSUE TITLE
No Footprints showing up in CvPCB

### ISSUE THREAD

**Issue by gabeart10** [KiCad/kicad-symbols#1065]
When I went into CvPCB to assign my components to their footprints, there were no footprints found when I clicked on a component. I know it it not filtering and all my libraries seem to be good, so I am at a loss. I am pretty new to Kicad so I may be just doing something really dumb. 
<img width="700" alt="screen shot 2018-10-13 at 10 31 01 am" src="https://user-images.githubusercontent.com/6414310/46906541-1c1ec500-ced3-11e8-8e9d-65e4f426c49f.png">
<img width="893" alt="screen shot 2018-10-13 at 10 31 51 am" src="https://user-images.githubusercontent.com/6414310/46906553-3c4e8400-ced3-11e8-93c0-db51ef46f677.png">

**Comment by gabeart10** [comment]
Also here is my Kicad version and OS
<img width="802" alt="screen shot 2018-10-13 at 10 35 33 am" src="https://user-images.githubusercontent.com/6414310/46906585-cc8cc900-ced3-11e8-9143-9faf387519c0.png">

**Comment by gabeart10** [comment]
Figured it out, Had to delate fp-lib-table and have it recreate it.

**Comment by poeschlr** [comment]
For the future: This is not the right place to ask user support questions. For that please head over to the forum: https://forum.kicad.info/
