### ISSUE TITLE
Travis check - missed S3.3.1

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-symbols#1066]
I noticed that the Travis symbol PR check didn't catch [S3.3](http://kicad-pcb.org/libraries/klc/S3.3/):
>Symbol body must have a line width of 10mil (0.254mm)

I noticed this during [this PR](https://github.com/KiCad/kicad-symbols/pull/1046).

**Comment by poeschlr** [comment]
Might be better to move this report over to the kicad-library-utils repo.
