### ISSUE TITLE
Footprint filters need to be adapted for the new footprint naming conventions

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#112]
I fear the footprint filters need to be adjusted for the new footprint naming convention. (Pitch -> P, ...)

**Comment by SchrodingersGat** [comment]
A lot of such changes could be made with find-and-replace, i think.

**Comment by poeschlr** [comment]
Yup atom would be powerful enough. I think we should do this either now and also require this for every further addition or we do it a few days before the release for all libs at once.

**Comment by poeschlr** [comment]
Part of this might have been fixed with https://github.com/KiCad/kicad-symbols/pull/150

**Comment by poeschlr** [comment]
@jkriege2 you where the author of #150. Did you fix everything mentioned here or is there still a problem?

**Comment by jkriege2** [comment]
I think it's done (just checked with a short search in Notepad++)
