### ISSUE TITLE
MAX40200 - Which library?

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-symbols#1191]
This is a quick one:

Which library do you think would be best to hold [MAX40200](https://datasheets.maximintegrated.com/en/ds/MAX40200.pdf)?

Potential locations:
- Analog_Switch
- Power_Protection
- Power_Management

![functional-diagram](https://user-images.githubusercontent.com/7242621/49247056-96e46680-f3d3-11e8-9641-ab93a55842a4.png)

**Comment by DanSGiesbrecht** [comment]
I've proceeded with using the **Analog_Switch** library. If anyone is opposed to this, please let me know. I'll leave this open for a few days.

**Comment by poeschlr** [comment]
Sounds good to me
