### ISSUE TITLE
Converting private made Eagle symbols to KiCad

### ISSUE THREAD

**Issue by Misca1234** [KiCad/kicad-symbols#1221]
Do we have scripts that convert own made Eagle symbols to KiCad ?

**Comment by poeschlr** [comment]
Nope. There is however a script that can convert them to geda. And you can trick kicad to import them by adding every part of a lib to an eagle project and import that with the new import eagle project feature.

**Comment by Misca1234** [comment]
Jee, I know about the schematic importer but i was hoping for individual symbols.
This guy Watsson that I have spoken at radiomuseum have a lot of own made valves schematics but only in Eagle, do you know if Eagle used "binary" representation of symbols or in plain text as kicad ?

**Comment by antoniovazquezblanco** [comment]
Can we close this issue @Misca1234 ?
