### ISSUE TITLE
Photomultiplier tubes

### ISSUE THREAD

**Issue by ferdymercury** [KiCad/kicad-symbols#1241]
I need to use schematic symbols of photomultiplier tubes, and I was about to start drawing symbols myself and submitting some pull requests.

I.e. a symbol like this:
![image](https://user-images.githubusercontent.com/10653970/49690833-25a86000-fb05-11e8-85ab-899e7dafd911.png)

However, I found that someone else did already that: https://www.ohwr.org/projects/pmtlib/repository

![image](https://user-images.githubusercontent.com/10653970/49690845-791aae00-fb05-11e8-8eb0-a9580a151066.png)

Do you think it is possible to merge these symbols into the official Kicad library? I am happy to help if they need modifications, please let me know.

Do you think also it would be doable to add a generic ngspice model for these abstract PMT symbols?

Thanks for the support.

**Comment by antoniovazquezblanco** [comment]
From the technical point of view I have never used theese kind of devices so I will not be able to judge but I guess that there should be no problem.
From the point of view of quality, please adhere to KLC as much as possible when submitting this.
From the legal point of view, you will have to get the original author to sign a re-licensing to CC-BY-SA 4.0 to be able to use the original files or you should start the symbols from scratch yourself.

About spice symbols, as said in https://github.com/KiCad/kicad-symbols/issues/464#issuecomment-438996841, we will not be accepting those for the time being.

**Comment by ferdymercury** [comment]
Thanks. Is there any kicad-symbol generator script repo?

I was thinking of making this type of symbol scriptable, so that depending on the number of dynodes, it just generates another one, but wider.

**Comment by poeschlr** [comment]
There are many different symbol generators. One generator is in the kicad-library-utils repo. It is currently used for generating the connector symbols.
There should also be a generator for generating the logic symbols. I think this one might live in one of the repos by @bobc.
There are also some that use csv data for creating simple black box symbols. (Kipart or similar)

**Comment by ferdymercury** [comment]
I will redraw them from scratch, because that library is old and does not follow KLC. What do you think of this first attempt?

![image](https://user-images.githubusercontent.com/10653970/49771181-f1c06c80-fcb5-11e8-9dc9-9de2d34ebe56.png)

Is there a way to make the symbol rectangle with rounded corners?

**Comment by poeschlr** [comment]
There is no easy way to make a symbol rectangle with rounded corners. Especially not one with filled background.

**Comment by ferdymercury** [comment]
Ok, let us leave it then square.
