### ISSUE TITLE
Analog_ADC: ADS1298_TQFP missing pin 28 (VCAP1)

### ISSUE THREAD

**Issue by gmsotavio** [KiCad/kicad-symbols#1242]
The ADS1298_TQFP symbol from Analog_ADC library is missing pin 28 (VCAP1).

![screenshot_2018-12-08_23-38-27](https://user-images.githubusercontent.com/10669626/49692469-ded95b00-fb42-11e8-9b01-7fb8f9f38f06.png)

**Comment by antoniovazquezblanco** [comment]
Thanks for the report and the PR!
