### ISSUE TITLE
LT3010-ADJ to be renamed to LT3010

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-symbols#1272]
> The part numbers could possibly be changed. For instance the adjustable one is LT3010 and not LT3010-ADJ which is a MPN that doesn't exist.

See https://github.com/KiCad/kicad-symbols/pull/1268

**Comment by JacobEFO** [comment]
I was wondering if I could possibly chip in here?

**Comment by myfreescalewebpage** [comment]
Issue solved with attached PR, closing right now.
