### ISSUE TITLE
RC1 Tagging

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-symbols#133]
I got notification from the devs that tagging release candidates of the library would be helpful. Unfortunately I do not know when RC1 will be branched.

**Comment by poeschlr** [comment]
We tagged all releases in the past and it is planned to tag them for the future as well.
As soon as we get information that rc1 is near we will tag the 3 repos.

**Comment by SchrodingersGat** [comment]
There are a small number of remaining legacy symbol libraries that need to be transferred as a matter of priority before we are ready to tag :)

**Comment by pointhi** [comment]
@SchrodingersGat 
and that stuff -> https://github.com/KiCad/kicad-templates

**Comment by Ratfink** [comment]
Closing this, as each of the relevant repositories has a `5.0.0-rc1` tag.
