### ISSUE TITLE
git CRLF issue: MCU_Microchip_SAMD local uncommitted changes

### ISSUE THREAD

**Issue by aewallin** [KiCad/kicad-symbols#1365]
Recently I'm getting a strange git error with MCU_Microchip_SAMD.lib and MCU_Microchip_SAMD.dcm

after a pull from upstream master I get local uncommitted changes in these files although I have never touched those parts or libraries??

**Comment by poeschlr** [comment]
Run diff. does it say something about crlf problems?

**Comment by myfreescalewebpage** [comment]
This new lib I have recently merged. KiCad do not complain on my side.

Joel

**Comment by myfreescalewebpage** [comment]
> the merge with possibly CRLF issues is #1107 ?

Yes.

I'm working on Windows, probably the submitter of this PR too. And you are probably on Linux ? The creation of some files may be a problem with CRLF yes.

**Comment by aewallin** [comment]
linux machine at work had no issues with this?

on another linux machine I am still stuck with the CRLF issue :(

**Comment by myfreescalewebpage** [comment]
I know git has configuration options about the line ending but I'm not an expert, a starting point to compare your two machines may be : https://help.github.com/articles/dealing-with-line-endings/

**Comment by aewallin** [comment]
meh, on my problematic machine I upgraded from git 2.7.x that comes with Ubuntu LTS16.04  to the latest available from https://launchpad.net/~git-core/+archive/ubuntu/ppa  which is 2.20.1

now the CRLF problem is gone.

**Comment by myfreescalewebpage** [comment]
Great !
