### ISSUE TITLE
LM358Z-2.5 in Reference_Voltage

### ISSUE THREAD

**Issue by davidsrsb** [KiCad/kicad-symbols#1369]
LM358 is a dual opamp.
I think that this is a typo for LM385Z-2.5

**Comment by myfreescalewebpage** [comment]
@davidsrsb probably I have missed one episode, but what do you mean ? Wrong name ? wrong device ? wrong lib ?

Cheers
Joel

**Comment by davidsrsb** [comment]
PR created
https://github.com/KiCad/kicad-symbols/pull/1376

**Comment by davidsrsb** [comment]
I am confused by the Travis error referring to there being no metadata
properties. This symbol is an alias and has no properties of its own

**Comment by myfreescalewebpage** [comment]
PR re-pushed at https://github.com/KiCad/kicad-symbols/pull/1383.

Merged, closing this issue.
