### ISSUE TITLE
RFM69, RFM95W and variants are in the wrong symbol library

### ISSUE THREAD

**Issue by gmsotavio** [KiCad/kicad-symbols#1391]
I noticed that RFM69 (RFM69?) and RFM95W (RFM9 * W) are in library RF_AM_FM. They are not either AM or FM radios. They are FSK (RFM69) and LoRa (RFM9*) radio MODULES. I think that the proper library is RF_Module. May I move them and submit a PR ?

**Comment by myfreescalewebpage** [comment]
@gmsotavio you are right, you can submit a PR, yes ! Thanks.

Joel

**Comment by myfreescalewebpage** [comment]
Closing this issue, work is actually on #1445
