### ISSUE TITLE
Guidance on new symbol

### ISSUE THREAD

**Issue by gcormier** [KiCad/kicad-symbols#1433]
So a quick question. I'd like to submit something for the LMH7324

1) Should I just do a trivial pull request to start a thread? I will probably need some assistance to pull this one off. But while we're at it... 

2) Thoughts on the best way to handle Vee pins? Stacked with one hidden?

![image](https://user-images.githubusercontent.com/8388983/51360532-0dc7e280-1a9a-11e9-937b-a10d4484944d.png)

![image](https://user-images.githubusercontent.com/8388983/51360551-1b7d6800-1a9a-11e9-9c2a-99e41088d272.png)

Sample schematic from the TI evaluation board:
![image](https://user-images.githubusercontent.com/8388983/51360613-52537e00-1a9a-11e9-8aa6-339def774e2c.png)

**Comment by poeschlr** [comment]
Vee stacked with one hidden is the right way to go here.

If it has more than one such unit then the power pins should be placed on their own unit.
