### ISSUE TITLE
incorrect pinout for Diode_Bridge:W005G

### ISSUE THREAD

**Issue by ppelleti** [KiCad/kicad-symbols#1440]
Here is the footprint for `Diode_THT:Diode_Bridge_Round_D9.8mm`:

![diode-bridge-round](https://user-images.githubusercontent.com/1080008/51431469-f8f46780-1bdd-11e9-9596-12c675558b3d.png)

Here is a diagram from the [datasheet](http://www.vishay.com/docs/88769/woo5g.pdf) referenced by the footprint:

![vishay-wog](https://user-images.githubusercontent.com/1080008/51431475-217c6180-1bde-11e9-9f46-af0bba159ed9.png)

By looking at these two images, I would conclude that the pinout is:

```
1 ~
2 +
3 ~
4 -
```

However, here is the schematic symbol `Diode_Bridge:W005G`, which references this footprint and datasheet:

![diode-bridge-round-schematic](https://user-images.githubusercontent.com/1080008/51431503-7c15bd80-1bde-11e9-85e2-7de9f1d3fe67.png)

According to this symbol, the pinout is:

```
1 +
2 ~
3 -
4 ~
```

So, it appears to me that something is wrong.

**Comment by jkriege2** [comment]
I think it is correct ... look at this view from the datasheet you linked:
![2019-01-19 21_41_31-woo5g pdf - adobe acrobat reader dc](https://user-images.githubusercontent.com/11967523/51432140-169fec00-1c33-11e9-8478-d3c8d13f2d64.png)

Also have a look at the photo here: https://uk.rs-online.com/web/p/bridge-rectifiers/6295153/

The lower drawing in your screenshot is the bottom-view I think ... so then the pinout should be OK? Can you countercheck?

**Comment by ppelleti** [comment]
> The lower drawing in your screenshot is the bottom-view I think ... so then the pinout should be OK? Can you countercheck?

Yes, you're right.  Sorry about that.
