### ISSUE TITLE
Footprint-filter for Mini-Circuits symbols should use Case-code (not LandPattern code)

### ISSUE THREAD

**Issue by aewallin** [KiCad/kicad-symbols#1442]
As noted in https://github.com/KiCad/kicad-footprints/issues/1308 the footprint filter for Mini-Circuits parts should use the case-code, not the land-pattern code.
This is done so that the filter will match both the "plain" footprint (no GND-zones/vias) and the LandPattern footprint.

The symbols affected are (more to be added, if found):

- [x] ADE-6
- [x] SXBP-140
- [x] LRPS-2-1

**Comment by myfreescalewebpage** [comment]
Issue solved in attached PR.
