### ISSUE TITLE
Missing symbols for Vigortronix VTX-214-010 family

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-symbols#153]
The footprint exists (`Converter_ACDC_Vigortronix_VTX-214-010-xxx_THT.kicad_mod`) but no symbols for the component.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco added VTX-214-010 with https://github.com/KiCad/kicad-symbols/pull/1648

**Comment by antoniovazquezblanco** [comment]
I will review it. Need some time but I will find it ;)

**Comment by antoniovazquezblanco** [comment]
Thank you @evanshultz! Faster than me ;)
