### ISSUE TITLE
Broken datasheet links for Linear Technology

### ISSUE THREAD

**Issue by calebreister** [KiCad/kicad-symbols#1547]
It appears that the datasheet links for most (if not all) of the Linear Technology ICs are broken since they were acquired by Analog Devices in 2017. This may be scriptable, but it may be easier (and more reliable) just to go through the library and fix all of the links manually.

**Comment by evanshultz** [comment]
Here are two examples. Search and replace may work.

LTC6362
Was: http://cds.linear.com/docs/en/datasheet/6362fa.pdf
Is: https://www.analog.com/media/en/technical-documentation/data-sheets/6362fa.pdf

LT1054:
Was: http://cds.linear.com/docs/en/datasheet/1054lfh.pdf
Is: https://www.analog.com/media/en/technical-documentation/data-sheets/1054lfh.pdf

**Comment by evanshultz** [comment]
Thanks for the report. This has been resolved with https://github.com/KiCad/kicad-symbols/pull/1562 and https://github.com/KiCad/kicad-symbols/pull/1563. Thank you @lorem-ipsum !
