### ISSUE TITLE
Raspberry Pi - Computer Module

### ISSUE THREAD

**Issue by jneiva08** [KiCad/kicad-symbols#1629]
Have idea existed Symbol PR for Raspberry Pi - Computer Module, but can't find.

If needs to be created it should be created on MCU_Module?
It can be only one symbol or it should be separated by output type?

**Comment by evanshultz** [comment]
What is the purpose? There is an existing template, but it depends on what you want to do.

The issue of template vs footprint, and what they contain, is currently in flux. See https://github.com/KiCad/kicad-footprints/issues/1307 and other related discussions.

**Comment by myfreescalewebpage** [comment]
Maybe @jneiva08 wish to add the module as done for https://github.com/KiCad/kicad-symbols/pull/1195 ?

**Comment by jneiva08** [comment]
I'm speaking of this:

![Compute-Module](https://user-images.githubusercontent.com/8236353/54263025-b1e47c00-4567-11e9-94fc-1a92d31502f3.jpg)

Exist a [PR](https://github.com/KiCad/kicad-footprints/pull/1187) for the footprint from herostrat

I will need to use compute module for my job and for my friend.

**Comment by evanshultz** [comment]
I suppose MCU_Module would work. I don't see a more suitable place.

Here is how I'm thinking this would go:
- You could use a regular 200-pin connector symbol and a SODIMM footprint.
- However, having a specific symbol makes the pin functions more clear.
- This symbol could pick a SODIMM footprint as the footprint filter.
- A footprint for the module outline could be added and to the board along with the SODIMM header.
- Or a new footprint could be added that includes the SODIMM pads and the RPi board outline.

I don't know which approach is best. It seems this is not an area the official library has figured out yet (?).

@jneiva08 
How were you planning to approach this?

**Comment by myfreescalewebpage** [comment]
@evanshultz  that's exactly what we done together with the i.MX6 module I have proposed in #1195.

@jneiva I think you can:
- submit a specific symbol to detail te behavior of the pins. Something starting from the ViionSOM-6ULL of #1195 is great
- do not specify footprint, but only `*SODIMM*` footprint filter to allow SODIMM200 from several manufacturers to be selected

Joel

**Comment by myfreescalewebpage** [comment]
@jneiva08 does it answer your question ? Thanks.

**Comment by jneiva08** [comment]
Yes, I hope that during the weekend you can make the most of the symbol

**Comment by myfreescalewebpage** [comment]
So I'm closing the issue. Thanks.
