### ISSUE TITLE
Spelling Error KLC S5.2

### ISSUE THREAD

**Issue by b1ackmai1er** [KiCad/kicad-symbols#1658]
http://kicad-pcb.org/libraries/klc/S5.2/

*Neighter* the size of the exposed pad nor the size of the mask cutout are included.

Should be "Neither"

**Comment by fauxpark** [comment]
Please open an issue (or better yet, a PR!) in [KiCad/kicad-website](https://github.com/kicad/kicad-website). This repo is for the symbol libraries :)

**Comment by b1ackmai1er** [comment]
Done thanks.
