### ISSUE TITLE
Typo in description of the Display_Graphic library

### ISSUE THREAD

**Issue by f6fvy** [KiCad/kicad-symbols#1677]
Found by chance a typo in the description of the “Display_Graphic” symbol lib (in sym-lib-table). It should be:

- Pixel based color or **monochrome** displays.

instead of

- Pixel based color or **monchrome** displays.

**Comment by evanshultz** [comment]
Thanks for reporting this issue you found. Confirmed. Would you like to submit a PR to fix it?

At the same time `Pixel based` should be changed to `Pixel-based`.
