### ISSUE TITLE
Symbol for Connector with more then 40 Pins?

### ISSUE THREAD

**Issue by daviid5** [KiCad/kicad-symbols#1692]
Are there any Symbols for Connectors with more then 40 Pins?
I want to use the "Hirose_FH12-50S-0.5SH_1x50-1MP_P0.50mm_Horizontal", but is there any symbol, which I can user for this 50 Pin connector?
I can't find any :(

**Comment by evanshultz** [comment]
We have a bunch of them:
![image](https://user-images.githubusercontent.com/1936989/55195464-d0529600-5169-11e9-977e-59d2d2e8b6b8.png)

**Comment by poeschlr** [comment]
@evanshultz these are for dual row connectors not for single row ones like the FTSH linked to by @daviid5.

So yes technically one could use that dual row symbol but i feel it is confusing to readers of the schematic. Additionally the footprint filter of the dual row symbol is specifically designed for dual row footprints.

Meaning i agree that we might need to add some more symbols to be able to use all FFC footprints we have in the lib. We might however need to split it into multiple units at some pin number cutoff point.

**Comment by evanshultz** [comment]
OK. Closing.

BTW, a quick look at DigiKey shows there are FFC/FPC connectors up to [136 pins](https://www.molex.com/pdm_docs/sd/5025551360_sd.pdf) (not that we need symbols for all of them, of course).
