### ISSUE TITLE
CY7C65215 pin error?

### ISSUE THREAD

**Issue by magnusjjj** [KiCad/kicad-symbols#1717]
Hi.

While manually copying a schematic from paper, i noticed that pin 20 on CY7C65215-32LTXI is listed as VDDD.  According to the datasheet (https://www.cypress.com/file/129956/download) under the pin list, the schematic I am copying, and the example in there, it should be VSSD. Am I missing something? New to kicad (or any eda).

**Comment by myfreescalewebpage** [comment]
Hi @magnusjjj thanks for this issue, this is clearly a bug ! I propose myself to make the fix, since you are new to KiCad, this symbol has also several KLC violations. At the moment, you can connect pin 20 to VSSD according to me.
Cheers,
Joel

**Comment by magnusjjj** [comment]
Sounds good to me ;).

**Comment by myfreescalewebpage** [comment]
Pull request made.

**Comment by myfreescalewebpage** [comment]
Fixed in #1726
