### ISSUE TITLE
74xx.lib 74HC244, 74HCT244 has no tri-state output

### ISSUE THREAD

**Issue by JonathSpirit** [KiCad/kicad-symbols#1720]
74xx244 is a tri-state buffer but in the 74xx.lib only the 74LS244 is correct but the others (74HC244 and 74HCT244) have a simple output instead of tri-state output

**Comment by evanshultz** [comment]
Good catch.

This also affects 40244 in the 4xxx library.

Are you willing and able to submit a fix to correct the library?

**Comment by JonathSpirit** [comment]
Hey, sorry for the response time. I submitted my fix here #1738
But i dont found the 40244 in the 4xxx library that you saying.

**Comment by myfreescalewebpage** [comment]
Original report fixed, closing.
