### ISSUE TITLE
DS1267 in Potentiometer_Digital has pin 13 and 12 swapped

### ISSUE THREAD

**Issue by pyroesp** [KiCad/kicad-symbols#1753]
Datasheet:
![datasheet](https://user-images.githubusercontent.com/8619921/56171369-474eb200-5fe5-11e9-960c-64cca568763e.png)  
KiCad symbol:
![symbol](https://user-images.githubusercontent.com/8619921/56171370-47e74880-5fe5-11e9-89da-7e212dda5bb1.png)  

Unfortunately I just saw that, so my board will have a bodge wire.

**Comment by myfreescalewebpage** [comment]
@pyroesp thanks for this report and sorry for this bad news :( Are you able to make a pull request to fix it ? Else I can do it myself, for future users. Let me known.
Thanks,
Joel

**Comment by pyroesp** [comment]
Hey Joel,  
I didn't have time until today to make the pull request.  
Hopefully I've done it right.  

This is an old digital pot I needed to use in an old project.  
I'll be able to add a wire to the board to fix it, but yeah, I don't think anyone is ever going to use that part nowadays (except me).

Anyways, please check out pull request #1759 .

**Comment by myfreescalewebpage** [comment]
Pull request has been merged.
