### ISSUE TITLE
Web page or github page lisitng all the symbols?

### ISSUE THREAD

**Issue by E3V3A** [KiCad/kicad-symbols#1754]
It would be useful to have a clear pictorial list of all the different basic symbols.
I.e. a table with the symbol name and schematic symbol.

It would help saving some time having to look for alternative symbols with obscure names.

**Comment by aewallin** [comment]
are there python scripts that can read and render (PNG?) symbols and footprints?

**Comment by poeschlr** [comment]
I seem to remember there was a post on the forum where somebody made a website that could show kicad library assets.
I also seem to remember there was a post about a tool that could export a list of library assets with pictures to a pdf.

I can not find either of them right now. But you could make a post on the forum and ask if somebody has such thing lying around. (I think such a question is generally better served on the forum.)

https://forum.kicad.info/
