### ISSUE TITLE
BPW21 symbol connected to wrong pins of the package

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#1757]
originally reported in: https://github.com/KiCad/kicad-website/issues/402

datasheet: http://techwww.in.tu-clausthal.de/site/Dokumentation/Dioden/Fotodioden/BPW21-Fotodiode.pdf

**Comment by evanshultz** [comment]
Confirmed. Fix submitted at https://github.com/KiCad/kicad-symbols/pull/1783.
