### ISSUE TITLE
Invalid pinout for TXB0108DQSR

### ISSUE THREAD

**Issue by andreili** [KiCad/kicad-symbols#1764]
A-port - it's OK, and B-port - from another package!
![image](https://user-images.githubusercontent.com/1331777/56423095-30dd7a80-62b3-11e9-8a2e-d26f351e85f5.png) ![image](https://user-images.githubusercontent.com/1331777/56423107-3c30a600-62b3-11e9-974d-ff51fcd508b3.png)

**Comment by myfreescalewebpage** [comment]
Closing following merge of attached PR.

**Comment by andreili** [comment]
Merged to master.
