### ISSUE TITLE
KiCad 5.1.1 had a serious bug. Will never be officially released. Replaced by 5.1.2

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#1777]
See: https://lists.launchpad.net/kicad-developers/msg40218.html

And especially: https://lists.launchpad.net/kicad-developers/msg40227.html

I will therefore tag the same commit with 5.1.2 that was originally 5.1.1

**Comment by evanshultz** [comment]
5.1.2 is out so closing this.
