### ISSUE TITLE
Small question, why git/kicad modify thing that i don't want to

### ISSUE THREAD

**Issue by JonathSpirit** [KiCad/kicad-symbols#1802]
I just modified only one thing (the position offset on the 74LS374), and kicad change the position in the file of the 74HC14 (same data in a different place) that i never touch :/
so what do i do ? I commit the change as well ?

![chiant1](https://user-images.githubusercontent.com/48102745/56984012-4f7e2400-6b85-11e9-8b66-91aa1da87c36.PNG)
![chiant2](https://user-images.githubusercontent.com/48102745/56984018-51e07e00-6b85-11e9-8d41-3745a81fe32d.PNG)

My small change :(
![chiant3](https://user-images.githubusercontent.com/48102745/56984020-5442d800-6b85-11e9-9f04-91d0190cb861.PNG)

**Comment by evanshultz** [comment]
Yes, just commit it.

The devs have a bad habit (IMO) of changing the line ordering during save between various builds of KiCad. This is a common problem that we just deal with because we've seen it so many times.

**Comment by JonathSpirit** [comment]
ok thanks !

**Comment by poeschlr** [comment]
The best option would be to open the lib, save it without changing it (use the move command on a pin but place it at the same place to enable saving) check with git status if something changed. If it did make a separate commit with "saved with current stable" and then make your changes on a later commit. Makes it much easier for us maintainers to see what goes on. (We can then squash merge at the end to keep the master branch clean of such commits.)
