### ISSUE TITLE
INA138/INA168 Schematic symbol has incorrect pinout

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#181]
See old issue: https://github.com/KiCad/kicad-library/issues/1864

**Comment by jkriege2** [comment]
fixed there: https://github.com/KiCad/kicad-symbols/pull/238
![2018-01-28 16_28_15-greenshot](https://user-images.githubusercontent.com/11967523/35483949-8333771e-0448-11e8-9662-43475dbc3c27.png)
