### ISSUE TITLE
Triac symbols needs correction, or new symbol

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#182]
See old issue: Triac symbols needs correction, or new symbo

**Comment by jkriege2** [comment]
posted PR as a fix: https://github.com/KiCad/kicad-symbols/pull/239
![2018-01-28 16_41_11-symbol library editor - device d__kicad_kicad-symbols_device lib](https://user-images.githubusercontent.com/11967523/35484048-55f84c46-044a-11e8-933a-bc1c5560f3d1.png)
