### ISSUE TITLE
Symbol naming guideline

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#185]
Mostly already included in KLC v3.
original discussion see https://github.com/KiCad/kicad-library/issues/1398

@evanshultz if everything has been included in the new KLC feel free to close this. Otherwise please add a short summary of the missing parts.

**Comment by poeschlr** [comment]
@jkriege2 if you have some input about this feel free to chime in as well

**Comment by evanshultz** [comment]
Closing now since it seems to be working. There are already a few areas that need coverage, but let's handle them as they come up.
