### ISSUE TITLE
Symbol MCP6004 has wrong component name: L2902

### ISSUE THREAD

**Issue by wmzart** [KiCad/kicad-symbols#1882]
See the following screenshot:

![MCP6004](https://user-images.githubusercontent.com/11244469/58384355-32504000-7fe1-11e9-8b67-37c3c40a37a6.png)

**Comment by antoniovazquezblanco** [comment]
MCP6004 is an ALIAS of LM2902. This means that all the drawing and pin information is taken from LM2902 while datasheet, description and keywords are overriden by the values of MCP6004.

You can check that information in the library symbol properties dialog in the aliases tab.

I hope it helps!

**Comment by antoniovazquezblanco** [comment]
By the way, in this case, there is no issue with the library but if you wish to change the behaviour of KiCad so that it renders the aliases information you should report that at https://bugs.launchpad.net/kicad

Thank you!

**Comment by poeschlr** [comment]
My guess is that this would be classified as a new feature and would therefore not happen for v5. It makes little sense to implement anything alias related for v6 as the whole alias stuff will be dropped in favor of the inheritance stuff. (Or possibly also the new atomic stuff as suggested by seth. I am not yet convinced that we should use both the inheritance stuff and the atomic stuff)

**Comment by wmzart** [comment]
Thanks for pointing out the alias feature. In that case I will not file a bug report and wait for what is going to be implemented in v6.
