### ISSUE TITLE
Not all LED RGB combinations which are in use are in Device.lib

### ISSUE THREAD

**Issue by EeliK** [KiCad/kicad-symbols#1927]
RGB LED_ symbol group in Device.lib is missing some pin configuration combinations.

For example

Dialight 598-8810-307F,
http://www.dialightsignalsandcomponents.com/Assets/Brochures_And_Catalogs/Indication/SMT_selector_guide.pdf
page 12, "1208 Tri-Color (Fig 22)"

is GRBA, like some others in the same pdf document.

I wonder if all theoretically possible combinations should be there.

**Comment by evanshultz** [comment]
The library does not claim to have every single symbol or footprint and we are not in a position to take requests. If you would like to contribute the missing symbols that would be nice. :)

I'm closing this issue, not out of spite, but to prevent it from lingering since it's not actionable.
