### ISSUE TITLE
ATX PSU Symbol

### ISSUE THREAD

**Issue by jneiva08** [KiCad/kicad-symbols#2002]
Have made symbol for ATX12 V1.x (10 pins) and V2.x (24 pins).
I don't know where i shall put it.

The connector is used to connect PSU to motherboard.

**Comment by evanshultz** [comment]
I would say `Connector.lib` since it's not generic but it's a connector. Other similar connectors seem to be in that lib. What do you think?

**Comment by jneiva08** [comment]
It makes sense. Have already made [PR 2004](https://github.com/KiCad/kicad-symbols/pull/2004)

**Comment by antoniovazquezblanco** [comment]
Issuel solved
