### ISSUE TITLE
LM311 - open emitter pin 1 ERC fail 

### ISSUE THREAD

**Issue by StormTrooper** [KiCad/kicad-symbols#2020]
Application: KiCad
Version: 5.1.3-ffb9f22~84~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.18.0-25-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.22
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.4.0 with C++ ABI 1011

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

I'm running the latest symbols from Git and on the LM311 there is a issue on pin 1.

 Conflict problem between pins. Severity: error
Pin1 (power output) of component is connected to pin 1 (Open emitter) of U1

https://www.ti.com/lit/ds/symlink/lm211.pdf 

https://forum.kicad.info/t/lm311-open-emitter-pin-1-erc-fail/18216

Poster suggested In this case both pin 7 and pin 1 might be best as passive.

**Comment by evanshultz** [comment]
Yep. I just caught something similar on another part at https://github.com/KiCad/kicad-symbols/pull/1949.

Passive type should be fine for the collector and emitter pins. Would you be up for making a PR to correct this issue?
