### ISSUE TITLE
Motor/Fan_ALT looks mangled

### ISSUE THREAD

**Issue by pgrudzinski** [KiCad/kicad-symbols#2042]
![image](https://user-images.githubusercontent.com/8490243/62157022-7f67cf80-b30c-11e9-8420-c28b2c7e2cfb.png)
I'm not even sure how it was supposed to be looking.

**Comment by evanshultz** [comment]
Yikes! Thanks for submitting this issue!

Digging into the history, which required going back to the old repo, it appears the symbol was added at https://github.com/KiCad/kicad-library/pull/717 and an image is there.

But interestingly, the symbol changed even during the revs in the PR. I replicated the symbol from the initial commit of that PR and submitted https://github.com/KiCad/kicad-symbols/pull/2043.
