### ISSUE TITLE
LM4810 wrong datasheet

### ISSUE THREAD

**Issue by daviid5** [KiCad/kicad-symbols#2062]
Symbol of 'LM4810' contains Datasheet link to LM4811 (http://www.ti.com/lit/ds/symlink/lm4811.pdf)

**Comment by evanshultz** [comment]
Good catch. Thanks for taking the time to submit this issue.

Confirmed error at https://github.com/KiCad/kicad-symbols/blob/master/Amplifier_Audio.dcm. Datasheet should be http://www.ti.com/lit/ds/symlink/lm4810.pdf.

@daviid5 
Would you submit a PR to correct this?
