### ISSUE TITLE
Cypress CY7C65215A-32LTXI incorrect pin assocation

### ISSUE THREAD

**Issue by willcarroll7** [KiCad/kicad-symbols#2072]
This part in the default library lists pin 20 as a VDDD power supply input, however the datasheet lists pin 20 as a VSSD ground supply.

https://www.cypress.com/file/129956/download

**Comment by chschlue** [comment]
Which version?
Git master is fine.
![cy7](https://user-images.githubusercontent.com/40901018/62963240-e30bf580-be00-11e9-918e-f3bef046f972.png)

**Comment by chschlue** [comment]
https://github.com/KiCad/kicad-symbols/commit/55bce93f5ca9b73d0017bec7729f4c345e7ed320
https://github.com/KiCad/kicad-symbols/pull/1726
https://github.com/KiCad/kicad-symbols/issues/1717

Can be closed.

**Comment by cpresser** [comment]
Thanks for the research @chschlue
