### ISSUE TITLE
74LVC1G66 Bilateral Switch Has Missing Datasheet and Unspecified Footprint

### ISSUE THREAD

**Issue by Aliasmk** [KiCad/kicad-symbols#2074]
`74xGxx:74LVC1G66` has a 404'd datasheet link. 

Additionally, according to [this datasheet](https://assets.nexperia.com/documents/data-sheet/74LVC1G66.pdf) the pinout changes with different package types. I.e. for SOT353-1 and SOT753 packages, `Vcc` is pin 5. For SOT886, SOT891, SOT1115 and SOT1202, `Vcc` is pin 6, and pin 5 is `N/C`. 

No indication as to pinout is made in the description of the part, nor is a default five-pin footprint set. This may result in mistakenly assigning `Vcc` to pin 5 when using six-pin footprints.

**Comment by chschlue** [comment]
https://github.com/KiCad/kicad-symbols/pull/2076
