### ISSUE TITLE
LM339 gate arrangement isn't consistent

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#2105]
This is an annoying one.

I have found that different LM339 vendors in DIP, SOIC, SSOP, etc. (not QFN) packages don't use the same nomenclature for the gates, specifically with regards to gate 1 and 2.

Let's look at some datasheets for clarity. [TI's datasheet](http://www.ti.com/lit/ds/symlink/lm2901.pdf) has gate 1's output on pin 1:
![image](https://user-images.githubusercontent.com/1936989/63884423-04391e00-c98b-11e9-86e2-126a841c49da.png)

Irritatingly, [ST's datasheet](https://www.st.com/resource/en/datasheet/lm139.pdf) flips the pinout of gates 1 and 2 (gates 3 and 4 are consistent):
![image](https://user-images.githubusercontent.com/1936989/63884504-259a0a00-c98b-11e9-88d4-0d9d3876b489.png)

[ON Semi](https://www.onsemi.com/pub/Collateral/LM339-D.PDF) agrees with ST. So does [ROHM](https://www.rohm.com/datasheet/LM339F/lm393f-e). And so does the KiCad symbol.

There are other vendors of LM339s but those are the three vendors shown at DigiKey, Mouser, and Farnell so I figured that's enough to start this conversation.

Here is my biggest issue: Our symbol matches the ST/On Semi/ROHM pinout, but the linked datasheet is from TI. So looking at the datasheet in KiCad one could reasonably think the symbol is wrong. I couldn't justify multiple symbols but it can lead to confusion if someone is used to the nomenclature from a non-TI datasheet.

So here's my proposal. Would anyone support a PR to do the following:
- Switch our LM339 symbol to use the ST LM339 datasheet above (it is an ALIAS of LM2901).
- Switch our LM2901 symbol to use https://www.st.com/resource/en/datasheet/lm2901.pdf.
- Switch our LM2901 symbol to use https://www.st.com/resource/en/datasheet/lmv331.pdf (it is also an ALIAS of LM2901).

Doing that will make our symbol and datasheets for LM339 and related parts match.

**Comment by chschlue** [comment]
This doesn't seem critical to me as both versions are functionally equivalent, but I agree the linked datasheet should match the symbol.
