### ISSUE TITLE
Minicircuits RF transformers labelled with incorrect metadata

### ISSUE THREAD

**Issue by polwel** [KiCad/kicad-symbols#2264]
The transformers from the ADTxx series in the *transformers* library contain incorrect data in the description. For instance, the ADT9-1T is marked as 9-800MHz, when it is actually rated 1 - 250 MHz. Also the description says the footprint is CD637, though the symbol is actually assigned the correct CD542 footprint.

**Comment by DanSGiesbrecht** [comment]
Hi @polwel! Thank you for pointing this out. I have updated the descriptions and opened a [PR](https://github.com/KiCad/kicad-symbols/pull/2272).

**Comment by DanSGiesbrecht** [comment]
This has been resolved in the above PR. Thanks again!
