### ISSUE TITLE
Missing alias in connectors library

### ISSUE THREAD

**Issue by aurabindo** [KiCad/kicad-symbols#228]
Commit 2135c6433d4ecec8648f34c6ead40e3e19776e98 gives me a warning when opening my schematic:

```
15:36:34: Alias 'Conn_2Rows-67Pins' not found in library:

'/home/aj/kicad_sources/kicad_github/kicad-symbols/Connector_Generic.dcm'

at line 2037 offset 23
```

**Comment by poeschlr** [comment]
Is it possible that your copy is corrupted? I just tested the lib and i don't get a warning.
I also looked at the files and the mentioned dcm entry also exists in the corresponding lib file.

**Comment by bobc** [comment]
There appears to be mismatch in names? Conn_2Rows_67 vs Conn_2Rows-67Pins

**Comment by poeschlr** [comment]
Yes i opened the wrong project with the wrong set of libs activated. (My bad)
Fix will be committed shortly.

**Comment by jkriege2** [comment]
has been merged

**Comment by aurabindo** [comment]
I can confirm, closing the issue. Thanks for taking care of it pretty quickly
