### ISSUE TITLE
Error: PS1 pad NC not found in Converter_ACDC:Converter_ACDC_MeanWell_IRM-03-xx_THT

### ISSUE THREAD

**Issue by ctbenergy** [KiCad/kicad-symbols#2327]
Converter_ACDC.lib
DEF IRM-03-3.3
Pin name and pin number is reversed
change
X 5 NC -300 0 100 R 50 50 1 1 N
to
X NC 5 -300 0 100 R 50 50 1 1 N

**Comment by evanshultz** [comment]
Confirmed.

@ctbenergy 
Would you make a PR to fix this? Thanks for catching this error and reporting it.

**Comment by myfreescalewebpage** [comment]
PR merged, issue is closed.
