### ISSUE TITLE
NC7SB3157P6X does not have any connection to power

### ISSUE THREAD

**Issue by leechwort** [KiCad/kicad-symbols#2451]
![image](https://user-images.githubusercontent.com/4254582/72662694-af0daf80-39f2-11ea-8f17-5cf7ea3b4343.png)
as a result pins, 2 and 5 are not connected to the power rail. 
![image](https://user-images.githubusercontent.com/4254582/72662701-c9478d80-39f2-11ea-9220-5b7c9d2c18d7.png)
Is it normal? If not, I can submit pull request with fix:)

**Comment by chschlue** [comment]
This is a multi unit symbol. Unit B contains the power pins.

**Comment by leechwort** [comment]
Aha, understood!

**Comment by leechwort** [comment]
It is normal operation
