### ISSUE TITLE
Common mode filters symbols

### ISSUE THREAD

**Issue by aracosta1** [KiCad/kicad-symbols#2455]
Hello,
Currently in the library there is only one symbol for Common mode filters, EMI_Filter_Common_mode, but the pinout is not always correct for some manufacturers.

As an example Bourns use this pinout 
![image](https://user-images.githubusercontent.com/12937688/72682254-64139b00-3acb-11ea-8045-9e4bf85fb965.png)

but Wurth use this 
![image](https://user-images.githubusercontent.com/12937688/72682263-83122d00-3acb-11ea-8fde-1ae6a99d170a.png)

Could it be a good idea to add a pin ordering specifier to the symbol and create different symbols for different manufacturer pinout ?
The symbols can then be specified as **EMI_Filter_LL_1423** for the Bourns like types and **EMI_Filter_LL_1243** for the Wurth like types.

Any comment is welcome

Matteo

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-symbols/pull/2376. I'll add the one you mention above shortly since nobody has commented or assigned themselves to my PR yet.

Closing since this is a known issue with a fix PR submitted.
