### ISSUE TITLE
Analog_Switch ADG728 wrong Pin to signal assignment

### ISSUE THREAD

**Issue by kagehisa** [KiCad/kicad-symbols#2552]
In the official Datasheet the pinout is the following:
![Bildschirmfoto 2020-03-16 um 11 04 58](https://user-images.githubusercontent.com/37015428/76745570-636b4e00-6776-11ea-80de-5ee7f4c13a30.png)

In the Library the pinout for Signals 1 to 4 are correct but 5 to 8 are wrong.
![Bildschirmfoto 2020-03-16 um 11 08 33](https://user-images.githubusercontent.com/37015428/76745747-b04f2480-6776-11ea-9d73-a3d982e1c3f5.png)
Signal S8 should be on pin 9, S7 on pin 10, S6 on pin 11 and S5 on pin 12.
The other assignments are correct.

**Comment by cpresser** [comment]
Can confirm, that looks broken.
Would you provide a fix for that? It is a rather simple change and a good way to start contributing to the library.

**Comment by kagehisa** [comment]
Alright I will give it a try.

**Comment by cpresser** [comment]
There are some instructions over here: https://kicad-pcb.org/libraries/contribute/
