### ISSUE TITLE
Remove ATSAMD21G18A-AUT

### ISSUE THREAD

**Issue by cpresser** [KiCad/kicad-symbols#2563]
In https://github.com/KiCad/kicad-symbols/pull/2336 better SAMD21 symbols were added.
Also the suffix  `AUT` contains temperature and packaging information.

#2366 also contains `ATSAMD21G18A-A` which makes the `AUT` part a duplicate in the lib.

As soon as breaking changes are allowed the `AUT` part should be removed.

**Comment by aris-kimi** [comment]
@cpresser I did a pull request for this. I hope it helped.
