### ISSUE TITLE
LTC4317 should be moved into `Interface_Expansion`

### ISSUE THREAD

**Issue by polwel** [KiCad/kicad-symbols#2622]
The [LTC4317](https://www.analog.com/media/en/technical-documentation/data-sheets/4317fa.pdf) is an I2C adress translator with two downstream ports.

Arguably it would be a better fit for the `Interface_Expansion` library than `Interface` where it currently lives. `Interface_Expansion` contains a number of I2C multiplexers and switches, in particular also the LTC4314.

The discussion originated in PR #2577.

**Comment by cpresser** [comment]
Fun fact: I added that part  https://github.com/KiCad/kicad-symbols/pull/2195 (with my work-account)

**A PR for this should not be made until we are nearing a v6.0 release.**
 If we do a PR now it will most likely have to be re-based because of conflicts.
