### ISSUE TITLE
Issues with QRE1113 and QRE1113GR symbols and footprint associations

### ISSUE THREAD

**Issue by saviocmc** [KiCad/kicad-symbols#2623]
First of all, thank you all contributors very much for this awesome library!

Reference
-----------
The issues I found are related to the *Reflective Optical Sensors* **QRE1113** and **QRE1113GR** (same sensor with different leadform options), found in the library **Sensor_Proximity**.
Datasheet: https://www.onsemi.com/pub/Collateral/QRE1113-D.PDF

They are currently declared in the the [Sensor_Proximity.lib](https://github.com/KiCad/kicad-symbols/blob/master/Sensor_Proximity.lib) file [here (QRE1113)](https://github.com/KiCad/kicad-symbols/blob/166cde7a05b3e1077df4efe936f338f28066b231/Sensor_Proximity.lib#L395) and [here (QRE1113GR)](https://github.com/KiCad/kicad-symbols/blob/166cde7a05b3e1077df4efe936f338f28066b231/Sensor_Proximity.lib#L147)

And in the [Sensor_Proximity.dcm](https://github.com/KiCad/kicad-symbols/blob/master/Sensor_Proximity.dcm) file [here (QRE1113)](https://github.com/KiCad/kicad-symbols/blob/166cde7a05b3e1077df4efe936f338f28066b231/Sensor_Proximity.dcm#L87) and [here (QRE1113GR)](https://github.com/KiCad/kicad-symbols/blob/166cde7a05b3e1077df4efe936f338f28066b231/Sensor_Proximity.dcm#L93)

Issues
------
- The descriptions and footprint associations in the symbols are swapped. According to the [datasheet](https://www.onsemi.com/pub/Collateral/QRE1113-D.PDF), the QRE1113 is the Through Hole version and the QRE1113GR is the SMD counterpart. This description and footprint associations are currently inverted in the lib.

- The QRE1113GR is defined as an alias of the ITR8307-F43 [(*datasheet*)](https://everlighteurope.com/index.php?controller=attachment&id_attachment=5385), but the two devices have different pin number definitions. For instance, the *Anode* and *Cathode* pins of the IR LED are inverted in the two devices.

  - QRE1113
![image](https://user-images.githubusercontent.com/9142154/78894127-ea90a680-7a42-11ea-9389-e65ab9f5267c.png)

  - ITR8307-F43
![image](https://user-images.githubusercontent.com/9142154/78894184-085e0b80-7a43-11ea-887c-2298796ffcd4.png) 

  - *Obs:* The pin *numbers* of the two devices is different but the pin *layout* of QRE1113 and ITR8307-F43 are identical.

- The same problem is present in the definition of an alias of the QRE1113, the ITR1201SR10AR [(*datasheet*)](http://www.everlight.com/file/ProductFile/ITR1201SR10AR-TR.pdf).

Questions
-----------
1 - Is it OK to have an alias of a device with **different** pin number definition but same pin layout?
I personally think this is a great source for confusion.

2 - The QRE1113 [datasheet](https://www.onsemi.com/pub/Collateral/QRE1113-D.PDF) defines a third device, the QRE1114GR (identical to the QRE1113GR). I was not able to find it in the main component marketplaces or anywhere else in the market. Should it be added as an alias of the QRE1113GR anyway?

Suggestions
-------------

- First of all, the **Value field** of the QRE1113 and QRE1113GR symbols **MUST** be swapped, as it is currently a direct contradiction of the [datasheet](https://www.onsemi.com/pub/Collateral/QRE1113-D.PDF).

- Create dedicated individual symbols for each of the components: QRE1113, QRE1113GR, ITR8307-F43 and ITR1201SR10AR to **not** define them in terms of alias of each other, as **NONE** of them have, at the same time, the same pin numbers/layout and same footprint.
  - *Obs:* The [BPR-105F](http://www.ystone.com.tw/en/data/goods/IRPT/Photo%20Interrupters-Reflective%20Type.pdf) can continue be an alias of the ITR8307-F43 as they have the same pin numbers and same footprint.

- Create a THT footprint for the QRE1113 based on the footprint of the ITR8307-F43 but with the appropriate pin numbers.

I may submit a PR in a few days implementing these suggestion.

**Comment by chschlue** [comment]
> ## Questions
> 1 - Is it OK to have an alias of a device with **different** pin number definition but same pin layout?
> I personally think this is a great source for confusion.

I'm inclined to say that Everlight's numbering is definitely asinine (pin 2 mark anyone?).
That being said, we already have similar cases. The TO-92 footprint is numbered left to right, for example, while some manufacturers number their TO-92 parts right to left, leading to apparently wrong symbols.
In this case, I'd vote for adding an Everlight-specific FP using Everlight's numbering (because it's not a standard package anyway.

> 2 - The QRE1113 [datasheet](https://www.onsemi.com/pub/Collateral/QRE1113-D.PDF) defines a third device, the QRE1114GR (identical to the QRE1113GR). I was not able to find it in the main component marketplaces or anywhere else in the market. Should it be added as an alias of the QRE1113GR anyway?

If ON claims to offer that part, it's probably permissible to add it. But what's the point?

**Comment by saviocmc** [comment]
@chschlue thanks for the quick answer.

> In this case, I'd vote for adding an Everlight-specific FP using Everlight's numbering (because it's not a standard package anyway.

I agree. The [current SMD FP](https://github.com/KiCad/kicad-footprints/blob/master/OptoDevice.pretty/OnSemi_CASE100CY.kicad_mod) assigned to the SMD version of these devices is using the ON numbering (with pin 1 mark), so another one should be created for the ITR1201SR10AR using the Everlight's numbering.

On the other hand, the [current Through Hole FP](https://github.com/KiCad/kicad-footprints/blob/master/OptoDevice.pretty/Everlight_ITR8307F43.kicad_mod) assigned is using the Everlight's numbering. So another one should be created using the ON numbering for the QRE1113.

Do you agree with the creation of these two additional footprints?

Also, do you agree with this suggestion?

> - Create dedicated individual symbols for each of the components: QRE1113, QRE1113GR, ITR8307-F43 and ITR1201SR10AR to not define them in terms of alias of each other, as NONE of them have, at the same time, the same pin numbers/layout and same footprint.

**Comment by chschlue** [comment]
LGTM

**Comment by chschlue** [comment]
@saviocmc Are you still on this?

**Comment by saviocmc** [comment]
@chschlue I got busy the past few weeks, but can I manage to submit a PR this weekend.

**Comment by chschlue** [comment]
@saviocmc Will you be able to wrap this up by Tuesday?

**Comment by saviocmc** [comment]
Sorry about the delay. I'm going to get this done by tomorrow.
