### ISSUE TITLE
Issue with MAX13433EETD, Incorrect footprint association  

### ISSUE THREAD

**Issue by EAjonb** [KiCad/kicad-symbols#2641]
Symbol is currently linked to the DFN-14-1EP_3x4_P0.5 Footprint but should be DFN-14-1EP_3x3mm_P0.4mm_EP1.78x2.35mm

**Comment by JacobEFO** [comment]
Seems like you're right. 

The symbol MAX13432EETD and its alias MAX13433EETD both link to Package_DFN_QFN:DFN-14-1EP_3x4mm_P0.5mm_EP1.7x3.3mm, which is incorrect.

Link to [datasheet](https://datasheets.maximintegrated.com/en/ds/MAX13430E-MAX13433E.pdf)
Link to [footprint](https://pdfserv.maximintegrated.com/package_dwgs/21-0137.PDF)

Maybe you want do a pull request for the fix?
