### ISSUE TITLE
74LS139 incorrect pin numbering

### ISSUE THREAD

**Issue by TheJustMoose** [KiCad/kicad-symbols#2650]
There is some problem with 74LS139 symbol (IEEE).
I think it has incorrect pin numbering.
Pin 2 and 3 mixed up. Pin 13 and 14 too.

**Comment by chschlue** [comment]
Theoretically fixed in #2162 and included in 5.1.5. Closing.

Please reopen if there's still an issue.

**Comment by TheJustMoose** [comment]
Bug is still there.
I think that 74LS139 is not 74LS193.

**Comment by TheJustMoose** [comment]
Sorry, I do not see 'reopen' button.

**Comment by chschlue** [comment]
Oops, read it wrong.
