### ISSUE TITLE
LM4040 TO-92 pinout wrong

### ISSUE THREAD

**Issue by martinjankoehler** [KiCad/kicad-symbols#2662]
The pinout for the LM4040 TO-92 THT parts is wrong (see picture).

Data sheet: http://www.ti.com/lit/ds/symlink/lm4040-n.pdf (see page 4)

![7886952E-5965-498A-A8DF-F4175A987FB7](https://user-images.githubusercontent.com/29398377/79907687-4c291b80-841a-11ea-977c-d767fe67fffc.jpeg)

**Comment by chschlue** [comment]
Confirmed.
Are you willing to submit a fix?

**Comment by martinjankoehler** [comment]
> Confirmed.
> Are you willing to submit a fix?

OK, I've created PR #2663

**Comment by martinjankoehler** [comment]
Sorry, mea culpa: #2664
