### ISSUE TITLE
74LS241 incorrect gate symbol on pin 19 / OEb

### ISSUE THREAD

**Issue by heaton84** [KiCad/kicad-symbols#2668]
The default library has an inverted input for both output enable pins (1 / OEa and 2 / OEb), however in the '241 only OEa is inverted.

Refer to section 8.2 on the datasheet: http://www.ti.com/lit/ds/symlink/sn74ls241.pdf

This was an easy fix for me, just passing along so it can make its way into the official library someday.

**Comment by chschlue** [comment]
Confirmed.
The current symbol is correct for its alias 244, however, so it has to be split in two separate symbols.

Are you going to submit a fix?
