### ISSUE TITLE
US1A-US1M Described as Schottky Barrier Rectifier Diode

### ISSUE THREAD

**Issue by aris-kimi** [KiCad/kicad-symbols#2672]
Hi everybody.

US1A-US1M Diodes are described as Schottky Barrier Rectifier Diode but in the datasheet doesn't mention Schottky. It does mention Ultra-Fast recovery time though, i think this should change to General Purpose.
I am on my way to add US2xx and i think all those should end up as an alias for MRA4003T3G.

Is this ok to proceed?

**Comment by chschlue** [comment]
Confirmed.

**Comment by evanshultz** [comment]
Assume you meant parts at https://www.diodes.com/assets/Datasheets/ds16008.pdf.

Confirmation is above, and to add to that they should be fine to be an ALIAS of https://www.onsemi.com/pub/Collateral/MRA4003T3-D.PDF.
