### ISSUE TITLE
4082 Symbol Library Error

### ISSUE THREAD

**Issue by jjohnson873** [KiCad/kicad-symbols#2680]
Using Kicad version 5.1.5 and pulled the schematic library symbol for a 4082 “4000 series” logic device. The Kicad library 4082 “A” symbol has pins 2, 3, 4, 12 as inputs and pin 1 as an output. Pin#12 should be corrected to be pin #5. Confirmed with datasheet that the correct input pins to this 4-input AND gate should be pins 2, 3, 4 and 5.

**Comment by chschlue** [comment]
Confirmed, thanks.
