### ISSUE TITLE
74LS109: incorrect polarity on K input

### ISSUE THREAD

**Issue by alexisvl** [KiCad/kicad-symbols#2694]
74LS109 is [dual JK with inverted K](https://assets.nexperia.com/documents/data-sheet/74HC_HCT109.pdf), but 74xx:74LS109 shows noninverted K.

**Comment by chschlue** [comment]
Confirmed.
Are you willing to submit a fix?

**Comment by alexisvl** [comment]
Sure, I can get it

**Comment by alexisvl** [comment]
aargh, never mind — looks like the build I'm running can't save the modified symbol, something must have been broken when the new format stuff was added. I don't really have time to revert and rebuild right now.

**Comment by alexisvl** [comment]
...nope, actually it saved it correctly and _then_ crashed. Apologies for the noise, will open PR in a moment
