### ISSUE TITLE
Symbol AD8218xCP wrong footprint

### ISSUE THREAD

**Issue by jcyrax** [KiCad/kicad-symbols#270]
The AD8218xCP symbol footprint field and filter contains wrong footprints. It should be 3x2mm.
![image](https://user-images.githubusercontent.com/16546947/35727512-fb78e10c-0810-11e8-891d-67ee466dcc11.png)
Actual footprint design looks ok, just the wrong naming.
https://github.com/KiCad/kicad-footprints/issues/336

**Comment by Ratfink** [comment]
Fixed by #395.
