### ISSUE TITLE
Various library errors

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#272]
From https://github.com/KiCad/kicad-symbols/pull/269:
- [x] - Sensor_Magnetic.lib:AS5048*: bad FPfilter
- [x] - Reference_Voltage.lib:REF5020ADGK, Reference_Voltage.lib:LT6657AHMS8-2.5: FPfilter should be `MSOP*3x3mm*P0.65mm*`
- [x] - Memory_RAM.lib:AS6C1616: FPfilter should be `TSOP?I*18.4x12mm*P0.5mm*` or just `TSOP*18.4x12mm*P0.5mm*`
- [x] - Potentiometer_Digital.lib:DS1267_SOIC: bad text sizes and FPfilter missing trailing `*` and contains extra fields
- [x] - MCU_Microchip_PIC18.lib:PIC18F13K50-ESS: FPfilter should be `SSOP*5.3x7.2mm*P0.65mm*` and the default footprint should be `Package_SO:SSOP-20_5x3x7.2mm_P0.65mm` (period is an `x`)
- [x] - Memory_EEPROM.lib:AT24CS*: FPfilter should be `SOIC*3.9x4.9mm*P1.27mm*`
- [x] - Memory_EEPROM.lib:AT24CS*: pins are off grid (maybe Bob will be fixing this?)
- [x] - Memory_Flash.lib:AT45DB161-RC: FPfilter is missing
- [x] - Memory_Flash.lib:AT45DB161-RC: pins are off grid (maybe Bob will be fixing this?)
- [x] - Timer_RTC.lib:DS3231: Wrong stacked pin names
- [x] - Regulator_Linear.lib:AP2204MP-ADJ: footprint and FPfilter mismatch
- [x] - Interface_USB.lib:FT240XS: VCC and GND pins are bidirectional type
- [x] - Interface_USB.lib:FT221XS: FPfilter is apparently an ALIAS
- [x] - Power_Protection.lib:USB6B1: has two FPfilters with a default footprint
- [x] - MCU_ST_STM32.lib:STM32*: many are missing FPfilter
- [x] - Analog_DAC.lib:MC1408*: wrong default footprints and FPfilters
- [x] - MCU_Atmel_8051.lib:AT89*2051-SU: Loads of off-grid pins and no FPfilter
- [x] - Power_Management.lib:LM5051, Power_Management.lib:LT1641-1: FPfilter should be `SOIC*3.9x4.9mm*P1.27mm*`
- [x] - Regulator_Switching.lib:MIC2177, Regulator_Switching.lib:MIC2178: missing FPfilter
- [x] - Regulator_Switching.lib:ADP5070AREZ: FPfilter should be `ETSSOP*4.4x6.5mm*P0.65mm*`
- [x] - MCU_Atmel_AVR.lib:AT90PWM1-16SU: missing FPfilter
- [x] - MCU_Atmel_AVR.lib:AT90Sxxxx-4SC: many off-grid pins and missing FPfilter
- [x] - Analog_ADC.lib:ADS128D818: off-grid pins
- [x] - MCU_Atmel_ATTINY.lib: many symbols with off-grid pins and/or no FPfilter
- [x] - MCU_Microchip_PIC12.lib:PIC12LF1840T48-IST: appears to come in only TSSOP14 but FPfilter should be the default footprint and the default footprint is just wrong
- [x] - Driver_LED.lib:HV9961NG-G, Driver_LED.lib:HV9931LG-G, Driver_LED.lib:HV9961LG-G, Driver_LED.lib:HV9930LG-G: VIN pin should be Power Input type and multiple FPfilters with default footprint
- [x] - Driver_LED.lib:HV9972LG-G, Driver_LED.lib:HV9925SG-G: multiple FPfilters with default footprint
- [x] - Driver_LED.lib:HV9961NG-G, Driver_LED.lib:HV9925SG-G: missing pins
- [x] - Analog.lib:CAP002DG: needs FPfilter updated due to the footprint apparently being moved to a different library
- [x] - Transistor_FET.lib:IRF7404, Transistor_FET.lib:FDS6890A, Transistor_FET.lib:IRF8721PBF-1, Transistor_FET.lib:IRF7607PBF, Transistor_FET.lib:IRF7343PBF, Transistor_FET.lib:IRF7309IPBF, Transistor_FET.lib:FDS9934C: off-grid pin(s)

**Comment by strombom** [comment]
See pull request: https://github.com/KiCad/kicad-symbols/pull/275

I have tried to fix most of the issues above with those exceptions:

* Timer_RTC.lib:DS3231: Not sure how to solve this
* MCU_ST_STM32: Since those are script generated maybe the script should include footprint filter
* MCU_Atmel_ATTINY: A bit too many to fix now

**Comment by bobc** [comment]
I've addressed Memory_EEPROM.lib issues in #222

**Comment by Misca1234** [comment]
Timer_RTC.lib is addressed in 
https://github.com/KiCad/kicad-symbols/pull/307

**Comment by evanshultz** [comment]
@bobc 
Thanks!

@Misca1234 
The checks above correspond to me PR at https://github.com/KiCad/kicad-symbols/pull/276, and also includes that fix.

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-symbols/pull/276 and https://github.com/KiCad/kicad-symbols/pull/332 handle all but the memory and MCU issues.

**Comment by daab4848** [comment]
@evanshultz Do you know any PRs that are fixing the leftover issues from the above list? I wanted to pick a bone with one or a few of these issues.

**Comment by Ratfink** [comment]
#305 adds the missing FPFilters to the STM32 symbols.

**Comment by evanshultz** [comment]
@daab4848 
Thanks for volunteering! I believe fixing the Memory_* libraries should be valuable. I don't know if anybody is fixing them in the short-term, so if you want to check all those libraries locally and make fixes that would be great. Longer term I believe the memory libraries will be script-based. But that shouldn't stop us from fixing other errors now.

The Atmel libraries are, I believe, almost fully fixed with regards to footprints and FPfilters. Having that done makes it easier to do further changes because there's less chance of having branch conflicts. I believe https://github.com/KiCad/kicad-symbols/pull/340 is the last of those PRs, and so once that PR is merged you shouldn't have issues making fixes there.

Also, if you want to run the check scripts on the entire library you're welcome to fix anything you find. Surely there are still lots of symbols (and footprints, too!) which need work.

**Comment by evanshultz** [comment]
@Ratfink 
Great! I checked that item above since I think it's safe to assume once a PR is submitted it will be merged. That also helps to leave only items without an "owner" as unchecked above.

**Comment by daab4848** [comment]
See PR KiCad/kicad-symbols #366 for the Memory_Flash.lib:AT45DB161-RC fixes (short-term)

**Comment by daab4848** [comment]
@evanshultz See https://github.com/KiCad/kicad-symbols/pull/382 for MCU_Atmel_8051.lib:AT89xxxx-xx fixes

**Comment by Ratfink** [comment]
All items here are checked.  @evanshultz should this be closed now?

**Comment by evanshultz** [comment]
Yep. It seems you made the last few edits to the list, so I suppose that means the open items I last saw are closed. Thanks for the reminder!
