### ISSUE TITLE
STGIPSxxxxx Design help

### ISSUE THREAD

**Issue by aris-kimi** [KiCad/kicad-symbols#2768]
Hi everyone.

I'm about to add those ic's but i need some guidance about an appropriate symbol appearance.. I think from those three topologies the first is the best, or the third...

I am going to add this under Driver_Motor lib.

![stgips](https://user-images.githubusercontent.com/48727784/83331810-e6de0b00-a2a0-11ea-9c4c-efae429c8647.jpg)

**Comment by evanshultz** [comment]
https://www.st.com/resource/en/datasheet/stgips10c60.pdf is one datasheet.

The first will make the bootstrap caps awkward to wire up.

The last is the best of the above, IMO. But putting CIN on the right side would make it even better. And the OUTx pins could be Output type.

Additionally, page 14 of the datasheet above is another pin layout that looks good to me. I might even like it better than option three above.

Submitting a snippet of a schematic using the symbol in your PR might be a good way to show that the pin layout works nicely.

**Comment by aris-kimi** [comment]
I have made some changes to all so they can easily be exchanged. I think i should create a new lib though, named IGBT_Module, and put them in there instead of Driver_Motor, is this ok??

![stgips](https://user-images.githubusercontent.com/48727784/83362751-4f5de280-a39c-11ea-814d-dedd0fec8579.jpg)
