### ISSUE TITLE
Electrical type of DWM1000 VSS pins should be Power input, not Power output

### ISSUE THREAD

**Issue by gavanfantom** [KiCad/kicad-symbols#2856]
The schematic symbol for DWM1000 in RF_Module has all of the VSS pins set to the electrical type Power output. This causes ERC to fail, as these pins all need to be tied together.

The correct setting for all of the VSS pins is Power input.

**Comment by cpresser** [comment]
Would you be so kind and create a patch for that and open a PR. Then we can merge the fix upstream.

**Comment by gavanfantom** [comment]
This pull request sorts out the VSS pins and the I/O pins for the DWM1000. I had a go at giving the DWM1001 a similar treatment, but it seems to require more than a quick go over with a text editor, so I reverted most of my changes to that one. It should still be a (small) incremental improvement.
