### ISSUE TITLE
fairechildsemi.com links for datasheet are leading to a page that is not a pdf file

### ISSUE THREAD

**Issue by AymenLA** [KiCad/kicad-symbols#2895]
exemple : 
http://www.fairchildsemi.com/ds/LM/LM78L05A.pdf 
takes you to 
https://www.onsemi.com

this behavior is seen in linkes provided in "Regulator_Linear.dcm", I didn't check other symbol files.

**Comment by chschlue** [comment]
Yes, ON Semi was too lazy to set up decent redirects after purchasing Fairchild.
Fixes are welcome.

**Comment by AymenLA** [comment]
are links pointing to "alldatasheet.com" acceptable as a fix, or should we use only those provided by the manufacturer ?

**Comment by chschlue** [comment]
Manufacturer-provided datasheets are preferred (if available).
Next best would be large distributors (like Mouser, for example).

Please use dubious websites only as a last resort. (Alldatasheet is _kind of_ trustworthy, I guess)

**Comment by AymenLA** [comment]
Hi,

I might have a fix for the symbol files.
how do I submit my changes ? 
I've created a branch with this issue number but when I do a "git push" I get error 403 
"remote: Permission to kicad/kicad-symbols.git denied to AymenLA." ( this is normal .. )

how do I proceed to get the permission to push my branch ?
BR,

Aymen

**Comment by chschlue** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by AymenLA** [comment]
Hi,

here is the pull request :  [https://github.com/KiCad/kicad-symbols/pull/2902]

BR,
Aymen

**Comment by AymenLA** [comment]
Hi,

I've made a mistake regarding my last pull request : some changes where made and committed with my generic username and I didn't pay attention to that, this caused a problem for signing the CLI with that username, I've closed the pull request and I've made a new one.

issue-2895 correcting fairchildsemi.com dead links #2903 

BR,
Aymen

**Comment by AymenLA** [comment]
Hi,
just committed the change request,
BR,
Aymen
