### ISSUE TITLE
IRF9394M Is not a single FET

### ISSUE THREAD

**Issue by cpresser** [KiCad/kicad-symbols#2925]
See https://github.com/KiCad/kicad-symbols/pull/2894/commits/0812914afdab1de4eed8ee9b3184cc8e9cedbf1d#r473129452

The symbol is only a single FET, but there are two FETs in that device
![image](https://user-images.githubusercontent.com/17516572/90988187-5a867000-e591-11ea-82f2-8637f13c3140.png)

The footprint will also not match (Pin numbers need to be split):
![image](https://user-images.githubusercontent.com/17516572/90988180-4478af80-e591-11ea-94ff-6d3169cc178e.png)

**Comment by chschlue** [comment]
Looks like IRF939[45] were the only parts ever available in this package (both EOL).
So we can just alter this FP instead of adding a dual variant.
