### ISSUE TITLE
Error when openiing eechema

### ISSUE THREAD

**Issue by PatrickMULOT** [KiCad/kicad-symbols#2940]
When executing kicad and trying to open eschema, i have the following message:
"libwebkitgtk-3.0.so.0 ne peut ouvrir le fichier d'objet partagé- aucun fichier ou dossier de ce type." translated by google : 
"cannot open shared object file - no such file or folder."

I am under Ubuntu 20.04.1 LTS 64bits and Kicad 5.1.6
my pc : Asus k73SV Intel Core I7-2630QM CPU @ 2.00GHz x 8 - 1Tb SSD + 500Gb HDD

**Comment by evanshultz** [comment]
This repo is only for the official KiCad library, not the functionality of KiCad itself. I will close this issue.

You should post these kinds of questions at https://forum.kicad.info/ if you want to share you experience with other users and get their opinion and/or feedback. Wishlist items and bug reports for KiCad should be directed to https://bugs.launchpad.net/kicad.
