### ISSUE TITLE
GITHUB LOCKDOWN AND TRANSFER TO GITLAB

### ISSUE THREAD

**Issue by cederom** [KiCad/kicad-symbols#2965]
Hello world :-)

I can see there is a lockdown of the repo because of v6 preparations.. and the repository will be transferred to GITLAB.

Where should I put my current work? On GitLab??

The new GitLab repository does not seem to be there yet: https://gitlab.com/kicad/libraries/kicad-symbols/ returns 404..

Best regards :-)
Tomek

**Comment by evanshultz** [comment]
Hello.

PRs now get a message around this, for example your PR at https://github.com/KiCad/kicad-symbols/pull/2964. I assume that's what you're referring to.

For posterity and anyone else who seems this, here is the text:
![image](https://user-images.githubusercontent.com/1936989/91875746-c4a5b180-ec30-11ea-943c-2b970df619ab.png)

There is still work to be done on the librarian side for the GitLab migration, but all the instructions you need as a user are (hopefully) there. If you have set up your GitLab account then everything should be moved to GitLab automatically; you can then continue on GitLab or re-submit a PR.

**Comment by cederom** [comment]
Allright then, waiting until 20201001 KiCAD repositories are moved from GitHub to GitLab. Good choice :-)

**Comment by myfreescalewebpage** [comment]
@rjmaris will be done by the end of the day
