### ISSUE TITLE
just a patchfile with new symbol

### ISSUE THREAD

**Issue by rjmaris** [KiCad/kicad-symbols#3099]
[0001-add-MSP430FR247x.patch.txt](https://github.com/KiCad/kicad-symbols/files/5313394/0001-add-MSP430FR247x.patch.txt)

**Comment by aris-kimi** [comment]
I am sorry but i am not sure i understood correctly this issue.
Do you want to upload a new symbol?

**Comment by rjmaris** [comment]
Well, for a single instance... Yet, the V6 library repo has been launched.
