### ISSUE TITLE
X capacitor discharge IC library location

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#317]
@poeschlr @jkriege2 
Where should these ICs go? Their purpose is to quickly discharge capacitance stored in X capacitors when AC input voltage to a product is removed.

CAPZero parts are in the Analog library. These are Power Integrations parts which have been in our library a long time. See https://www.power.com/sites/default/files/product-docs/capzero_family_datasheet.pdf. They aren't analog parts IMO.

HF81 and TEA1708T were added later and merged into Power_Management (https://github.com/KiCad/kicad-library/pull/1790) and I think that's the correct library. Should the CAPZero parts be moved to Power_Management?

**Comment by jkriege2** [comment]
I fear I'm not really helpful on this:
I'm happy with both places, as I see arguments for both (don't really have a preference ...)

**Comment by evanshultz** [comment]
Analog doesn't apply, to me, because these are back-to-back FETs with a controller. There is at least a counter inside them. and a counter is a fundamental digital circuit.

**Comment by poeschlr** [comment]
Power management seems like a reasonable place to put them.

If this can be done before rc2 then they should be moved. After rc2 i think we should limit ourselfs to fixing klc issues, fixing bugs and adding new things. 
Major reorganization tasks should then be put of until we branch in preparation for v6. (I think we should give users as stable a lib as possible. Even if this limits some of the things we might want to do.)

**Comment by evanshultz** [comment]
Sure! PR submitted at https://github.com/KiCad/kicad-symbols/pull/356. And I just noticed that I forgot to use my own fork. Oops!
