### ISSUE TITLE
Q: Are these libraries compatible with KiCad 4 and/or nightly builds?

### ISSUE THREAD

**Issue by mpkopec** [KiCad/kicad-symbols#323]
This may be a stupid question but I am wondering if when creating schematic and adding new items to the lib using current version of KiCad I can use and contribute to _this_ library.

**Comment by jkriege2** [comment]
They are meant for v5 (and nightlies), but some symbols/footpritns will work with v4 ... some won't, as new features of the file formats are used. Especially you may not see many of the metadata of symbols (DCM-files) in v4.

See https://github.com/KiCad/kicad-symbols/blob/master/README.md

**Comment by mpkopec** [comment]
Thanks a lot!
