### ISSUE TITLE
migrating to v5 libs

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-symbols#329]
Hi, I want to migrate to latest libs and I noticed, that many symbols were migrated to different libs. There are some .json files which describes probably all those migrations.

Is there any simple way to use those .json files to update symbol names in my .sch files?

**Comment by poeschlr** [comment]
The json file contains most migrations but not all of them. I do not know of a script that does this for you. You could re-purpose parts of the symbol moving script found in the kicad-library-utils repo.

Another thing to keep in mind: We did not only move/rename the symbols. Some of them have other changes. (Example: Logic symbols now have a separate power unit and their size did change.)

**Comment by diggit** [comment]
Ok, I've done migration by hand. `sed` did most of the job.
