### ISSUE TITLE
Atmel MCU library issues

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#361]
- [x] Many pins have wrong text sizes (should be 50mil).
- [x] Many have pins off grid.
- [x] Many symbols have pin name position offset greater than preferred (should be 20mil).
- [ ] Some pin types may be wrong.
- [x] Some are off center.
- [ ] A few are missing metadata.

**Comment by daryl-t** [comment]
Just submitted my first pull request - waiting to see if my alterations are correct and if everything checks out OK I can start on these.

**Comment by Ratfink** [comment]
Most of these changes are already done in #373.

**Comment by Ratfink** [comment]
Closing this, as the task list has moved to #387.
