### ISSUE TITLE
STM32L051C6T (48pin) 36 pin name is wrong

### ISSUE THREAD

**Issue by KorsarovYu** [KiCad/kicad-symbols#378]
36 pin name is VDDIO2
in the library has name VDD_USB
in this MCU no USB present.
Thank you.

**Comment by Ratfink** [comment]
Thanks for reporting this!  The STM32 library is currently being overhauled in #305, and that PR will fix this problem once it's merged.

**Comment by poeschlr** [comment]
@Ratfink i assume this is now fixed. If so could you close it?

**Comment by Ratfink** [comment]
Ah, yes it is!  Thanks for reminding me to close this.
