### ISSUE TITLE
MCP 23016 has wrong pins in the library

### ISSUE THREAD

**Issue by un23** [KiCad/kicad-symbols#393]
Hello,

in legacy/microchip.lib, the pinout of the 23016 is not completely correct. Pin 10 is mentioned twice, but the ground pin 8 is not connected at all. This is also wrong in the 4.0 repository.

Regards
  un23

diff --git legacy/microchip.lib legacy/microchip.lib
index ed1053e..bcc2d01 100644
--- legacy/microchip.lib
+++ legacy/microchip.lib
@@ -162,8 +162,8 @@ X GPB2 4 -500 600 100 R 50 50 1 1 B
 X GPB3 5 -500 500 100 R 50 50 1 1 B
 X ~INT 6 500 300 100 L 50 50 1 1 O
 X GPB4 7 -500 400 100 R 50 50 1 1 B
+X GND 8 0 -1000 100 U 50 50 1 1 W
 X CLK 9 500 800 100 L 50 50 1 1 I
-X GND 10 0 -1000 100 U 50 50 1 1 W
 X TP 10 500 700 100 L 50 50 1 1 O N
 X VCC 20 0 1000 100 D 50 50 1 1 W
 X GPB5 11 -500 300 100 R 50 50 1 1 B

**Comment by Ratfink** [comment]
Fixed in #396.
