### ISSUE TITLE
Datasheet defined twice?

### ISSUE THREAD

**Issue by arildj78** [KiCad/kicad-symbols#465]
It looks to me as if a link is supposed to be supplied to the component datasheet in two different places.

Symbol->Fields...->Datasheet->Field value
Symbol->Properties...->Description->Documentation File Name

Am I missing something or is this due to the recent redesign of the library?

**Comment by jkriege2** [comment]
For the official libs we only use the latter option: http://kicad-pcb.org/libraries/klc/S6.2/

**Comment by arildj78** [comment]
Thanks.
Is the `Datasheet field` and the `Show Datasheet` button in `Field Properties` a legacy function?

**Comment by poeschlr** [comment]
Yes. As far as i am aware kicad 5 will fill the datasheet field from the dcm file when placing a symbol in eeschema (only if the field is empty).

More details see this mailing list conversation: https://www.mail-archive.com/kicad-developers@lists.launchpad.net/msg25829.html

I think this is the patch that got merged. (But there could be slight differences) https://www.mail-archive.com/kicad-developers@lists.launchpad.net/msg25887.html
