### ISSUE TITLE
Problems with regulator libs

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#54]
- Wrong footprints assigned.
    - Converters_DCDC_ACDC has been split in Converter_DCDC and Converter_ACDC
    - multiple symbols reference `Package_TO_SOT_SMD:TSOT-23-6_MK06A`, this does not seem to exist under that name any more.

Electrical pin types for some of these symbols might be wrong.

More details see travis report of the PR that transferred these libs.

**Comment by jkriege2** [comment]
The package is simply called `Package_TO_SOT_SMD:TSOT-23-6`

**Comment by antoniovazquezblanco** [comment]
Convertes have already been fixed by my MRs a while ago AFAIK.

A list of detailed issues with footprints has been created in this repo (See #28).

For that reason I vote in favor of closing this issue.

**Comment by myfreescalewebpage** [comment]
Agree with @antoniovazquezblanco too, closing.
