### ISSUE TITLE
Wrong pin numbers for Transistor_FET:IRF740

### ISSUE THREAD

**Issue by excsniper** [KiCad/kicad-symbols#642]
It looks like the D and S pin numbers for IRF740 need to be swapped.
![image](https://user-images.githubusercontent.com/2542314/40809138-6ab41d64-64f7-11e8-81e9-efb9cf33b7f6.png)

**Comment by evanshultz** [comment]
Yep, it's wrong. What the...

I also see a line missing from the gate pin to the vertical line.

Will be fixed when https://github.com/KiCad/kicad-symbols/pull/643 is merged.

Thanks for pointing this out.

**Comment by excsniper** [comment]
Cool, thanks for looking into it.
