### ISSUE TITLE
Strange behaviour of the Cvpcb

### ISSUE THREAD

**Issue by Misca1234** [KiCad/kicad-symbols#648]
I am not sure if you have already seen this or already reported and I guess it is not a library issue really but a program one.

It seems that Cvpcb have difficulties with foot prints where the size of the pad is not 3 numbers

I have made a symbol ESP8089 which I associate with the "wrong" footprint 
(just to show that there is not an error with the symbol or so, the strange behaviour is described further down.)

![bild](https://user-images.githubusercontent.com/25547797/40885035-69066038-671f-11e8-98c4-69c2991e6b15.png)

![bild](https://user-images.githubusercontent.com/25547797/40884990-81120d04-671e-11e8-8970-677beba8b841.png)

![bild](https://user-images.githubusercontent.com/25547797/40884991-865f87be-671e-11e8-8cc9-7e7e20ad91da.png)

If I run the Cvpcb I get the following result (as expected)

![bild](https://user-images.githubusercontent.com/25547797/40885067-d0b13780-671f-11e8-9b25-5cff4fb6b707.png)

But if I change to the more correct foot print, QFN-32-1EP_5x5mm_P0.5mm_EP3.6x3.6mm
I get the "wrong" behaviour

![bild](https://user-images.githubusercontent.com/25547797/40885002-d0c703d6-671e-11e8-8354-62bc5257f505.png)

![bild](https://user-images.githubusercontent.com/25547797/40885004-d803ad20-671e-11e8-868c-a7f06c7bab91.png)

![bild](https://user-images.githubusercontent.com/25547797/40885022-31972b50-671f-11e8-99e5-e6135900e0c4.png)

It does not longer "catch" anything with the foot print filter

**Comment by Misca1234** [comment]
Something is very strange here, here is a screen shoot of the footprint, the pin number is way wrong

![bild](https://user-images.githubusercontent.com/25547797/40887600-88ad2a80-674b-11e8-9c2f-134476965eb9.png)

The only one using that footprint, is nRF52810-QCxx in MCU_Nordic.lib
Shall I fix this footprint in same push as the symbol I want to push using this foot print ?

**Comment by evanshultz** [comment]
@Misca1234 
Good find. So this doesn't have anything to do with CvPcb.

Yes, please fix the footprint. It won't be in the same PR as the symbol, but a complementary PR would be nice.

@poeschlr @Ratfink 
This footprint was added at https://github.com/KiCad/kicad-footprints/pull/518. I suspect the pin array feature was used four times but the starting pin number wasn't incremented on each row of pins and instead left at `1`. Maybe it's best to show copper pads and pad numbers (not just for us but all contributors) so something like this can be caught at a glance? https://github.com/KiCad/kicad-footprints/pull/612 is another one where the copper wasn't enabled during the screenshot and without that info this kind of thing may be more likely.

**Comment by Ratfink** [comment]
Aw gosh darnit, I merged that one!  I was probably expediting the review because of all the work to fix #520, got lazy, and didn't load it in KiCad before merging.  Since I'm responsible for that footprint being merged, I'll fix it.

**Comment by Misca1234** [comment]
>So this doesn't have anything to do with CvPcb.

No, it seems that the pad numbering messed stuff up for the Cvpcb.

> I'll fix it.

Ok, then I wont do anything with it then

**Comment by poeschlr** [comment]
And i created it so... Wasn't my best hour i guess.
