### ISSUE TITLE
Where should chips go that hold a unique id?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#65]
Currently we have 3 such chips from Maxim. Where to put them?
Example chip: http://pdfserv.maximintegrated.com/en/ds/DS2401.pdf

Edit: maybe something like Memory_ReadOnly, or Periphery_ID

**Comment by jkriege2** [comment]
Maybe `Memory_SerialNumber` or `Memory_UniqueIdentification` (But I think SerialNumber is more understandable ...?)

**Comment by SchrodingersGat** [comment]
What about `Memory_ID` because it's not "really" a serial number (splitting hairs, I know).

**Comment by bobc** [comment]
The clue is in the question? - Memory_UniqueID.

**Comment by SchrodingersGat** [comment]
Let's go with `Memory_UniqueID`. Thanks @bobc

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/KiCad/kicad-symbols/pull/79
