### ISSUE TITLE
nxp pca9685bs pins mismatch

### ISSUE THREAD

**Issue by firebladed** [KiCad/kicad-symbols#662]
the pins for the HVQFN28 on the  pca9685bs don't match the datasheet

https://www.nxp.com/docs/en/data-sheet/PCA9685.pdf (page 6)

it appears to be using the pins for the pca9685pw which are different to the pca9685bs

in https://github.com/KiCad/kicad-symbols/blob/master/Driver_LED.lib

i can correct my own version but im still using version 4 and saving it appears to alter other things

**Comment by firebladed** [comment]
I believe  this a correctly numbered PCA9685bs for v4
[pca9685bs.lib.txt](https://github.com/KiCad/kicad-symbols/files/2098680/pca9685bs.lib.txt)

**Comment by firebladed** [comment]
this should be it
#691

**Comment by evanshultz** [comment]
Fix merged.
