### ISSUE TITLE
LTC4417CGN using QFN instead of SSOP

### ISSUE THREAD

**Issue by eclecticc** [KiCad/kicad-symbols#664]
The datasheet for LTC4417 is here: http://www.analog.com/media/en/technical-documentation/data-sheets/4417f.pdf

The symbol currently in the library for LTC4417CGN is for the QFN version, which should be LTC4417CUF.  LTC4417CGN is an SSOP.

I'm just learning KiCad now, but will attempt to submit a PR with the fix.

**Comment by eclecticc** [comment]
In #665

**Comment by eclecticc** [comment]
#672

**Comment by antoniovazquezblanco** [comment]
Thank you for the fix @eclecticc!
