### ISSUE TITLE
W10: Navigating through footprint editor, while changing footprint filters of a symbol

### ISSUE THREAD

**Issue by RensBloom** [KiCad/kicad-symbols#690]
Hi,

When I am adding footprint filters to a symbol in the Symbol Library Editor, I would like to be able to navigate through the Footprint Library, such that I can check what footprints exist in the library. Luckily I have multiple screens and we can open both the Symbol Library Editor and the Footprint Editor. So far, so good.
One issue: when the symbol properties window is open, the whole footprint editor is unable to respond (to mouse clicks or keyboard presses), so I can not navigate through the library. Used system runs on Windows 10. I don't know it is would be possible to build the UI such that both screens can respond, otherwise I have the following idea.
It would be great to have a search functionality in the footprint filter tab in the symbol properties, to test footprint filters and see what results do match a certain footprint filter.

I hope somebody wants to implement this enhancement to adding new components in the library!

![image](https://user-images.githubusercontent.com/5883286/41766661-e24662e4-7607-11e8-8386-b4c65382937e.png)

**Comment by poeschlr** [comment]
This is not the right place to post this. Head over to the bugtracker for feature requests or to the forum for tips on how do to things.
- https://bugs.launchpad.net/kicad
- https://forum.kicad.info/
