### ISSUE TITLE
SOT-23 footprint filters

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#697]
I just noticed this in Diode.lib, but surely it exists elsewhere. If the footprint filter is `SOT*23*`, then `SOT-223` will be caught as well as the intended `SOT-23`. The footprint filter should be `SOT?23*`.

There may be other similar cases where the footprint filter is greedy. I can't think of any right now, though...

**Comment by RensBloom** [comment]
TO-packages have the same issue, e.g. `TO*5*` that I see in a list of all footprint filters in the library.
