### ISSUE TITLE
Kicad 5 release immenent. I might not be able to tag the libs myself. Help needed

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-symbols#712]
Wayne just announced that the kicad 5.0.0-rc3 will be tagged shortly. After one week of testing periode kicad 5 will be released (if nothing critical is found till then.)

It might become necessary that one of you guys needs to tag the libs with 5.0.0 as i am out of country around that time. (I am in London from 30th of June till 10th of July for shell eco marathon. I am not sure if i will have internet access during that timeframe. Especially June 9th and June 10th will be without internet as I will be driving home from london.)

**Comment by evanshultz** [comment]
Yay! And have fun!

Of course we'll get it done if you're not able. @Ratfink, I'd be happy if you volunteer.

**Comment by poeschlr** [comment]
Forgot to link to the mailing list: https://lists.launchpad.net/kicad-developers/msg36374.html

**Comment by Ratfink** [comment]
You want li'l ol' me to make the 5.0.0 tag?  Aw shucks.

I'd be delighted.  Is there anything that will have to be done other than creating the tag?

**Comment by poeschlr** [comment]
Just make sure that there are no half merged pull requests before creating the tag. (Example if somebody merged the symbol PR but not the footprint PR.)

Also give the tag a nice comment if possible. (Bonus points for adding release notes here on the github webinterface such that it looks nice on the release pages.)

**Comment by evanshultz** [comment]
Seems this is no longer needed.

**Comment by poeschlr** [comment]
Yes i am back. But a heads up: wayne just tagged the source code (even though he mentioned just yesterday that the tagging date will be the 20th. I will check the libs more closely tomorrow CET. If everything seems ready by then i will tag the release.)

**Comment by Shackmeister** [comment]
If I understand it correctly the 20th was meant so the librarians, translators etc would have 1 week to finish up before release.
If this is the case, could we perhaps wait 1 week before tagging the libraries?

**Comment by stambaughw** [comment]
I'm fine with that as long as we don't go past next Friday.
