### ISSUE TITLE
Switchup of Pin 25 and Pin 26 in ESP8266EX symbol

### ISSUE THREAD

**Issue by cyber-murmel** [KiCad/kicad-symbols#744]
Between version ec2049abefa9126e13f618ed6a588fb88f0db670 of the repo's `MCU_Espressif` library and version 5.8 of the [data sheet](https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf) of the the `ESP8266EX` is a disparity for pin 25 and pin 26.
![symbol](https://i.imgur.com/LTuhyin.png)
![datasheet](https://i.imgur.com/OsmYbxV.png)

**Comment by Ratfink** [comment]
Good catch!  I just merged the fix, thanks a bunch.
