### ISSUE TITLE
Naming for expansion devices

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/kicad-symbols#77]
Currently I/O expanders are sorted into Interface_Expansion however a possible alternative name should be considered which covers:

* Port expanders
* Shift registers

**Comment by poeschlr** [comment]
Original discussion in this PR: https://github.com/KiCad/kicad-symbols/pull/73

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat @poeschlr what about this now we are working on V6 ? I'm personally happy with the existing library names. Joel

**Comment by evanshultz** [comment]
I'm good with the status quo also.

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat ping! Thanks

**Comment by SchrodingersGat** [comment]
Pong! I'm happy with the current naming too.

**Comment by myfreescalewebpage** [comment]
Ok, I think we can close this issue now :)
