### ISSUE TITLE
Incorrect footprints in Isolator.lib

### ISSUE THREAD

**Issue by Ratfink** [KiCad/kicad-symbols#792]
As reported by @alaut at https://github.com/KiCad/kicad-symbols/issues/520#issuecomment-409347596:

>It appears to me that TLP291-4 and others in the __Isolators.lib__ library are associated with the wrong footprints. I'm not nearly experienced enough to make any reliable attempt to correct through these yet... though I plan to contribute sooner than later.
>
>For example. I'm not sure if technically the footprint associated with LTV-847S is correct or within a certain tolerance. Datasheet indicated 9mm width, footprint appears to be 9.53mm. I'm inclined to believe I'm wrong here.
>
>TLP291-4 is definitely wrong though by a lot unless I'm missing something. According to the [datasheet](http://bit.ly/2Oyhfaj), the pitch is 1.27mm not 2.54 as associated in _Package_DIP:SMDIP-16_W7.62mm_

I agree that TLP291-4 is definitely wrong, and LTV-847S looks suspicious as well.

**Comment by evanshultz** [comment]
Fixed in #1177.
