### ISSUE TITLE
Incorrect type of R,S pins in 4013, 4027 in Logic_CMOS_4000

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-symbols#85]
A user on https://forum.kicad.info/t/new-logic-cmos-4000-library-4013-symbol/8923 has noticed incorrect pins on these parts : 

> The R and S inputs on the 4013 in the new library are marked "active low". HEF4013B has active high C(lear) and S(et) inputs, according to the Product spec. 

This error was introduced when the parts were scripted with symgen.

I will submit a PR to fix this soon.

**Comment by antoniovazquezblanco** [comment]
Shouldn't this issue be closed?

**Comment by bobc** [comment]
Yes, I believe it is now fixed.
