### ISSUE TITLE
4000 series CMOS 4082 schematic symbol is incorrect

### ISSUE THREAD

**Issue by Agent24** [KiCad/kicad-symbols#850]
In library 4xxx_IEEE, the Dual 4-input AND gate, 4082 has an incorrect pinout.
For Unit A, what should be Pin 5 is a duplicate Pin 12 from Unit B. Unit B itself is correct.

**Comment by antoniovazquezblanco** [comment]
Thank you very much @Agent24 !

Will you be willing to open a pull request in order to fix this?

**Comment by antoniovazquezblanco** [comment]
PR submited at https://github.com/KiCad/kicad-symbols/issues/850
