### ISSUE TITLE
In which library should I place INTAN chip familly

### ISSUE THREAD

**Issue by penoud** [KiCad/kicad-symbols#870]
Dear all, I use INTAN TECHNOLOGIES IC. I plan to design symbols for the RHD2000 familly. 
http://intantech.com/products_RHD2000.html 
In wich library should I place them?
Thanks for your help

**Comment by poeschlr** [comment]
Either in some amplifier or interface lib. As i do not fully understand the function of these products i can not really be of much further help without investing time into research.

**Comment by penoud** [comment]
What about Analog_ADC since it's the main function of the chip?

**Comment by penoud** [comment]
Thanks for your feedbacks
