### ISSUE TITLE
Need symbol for arduino mega

### ISSUE THREAD

**Issue by ajlaut** [KiCad/kicad-symbols#897]
The arduino uno symbol is very useful and better defined with DRC than that available via the Sparkfun/Ki-Cad librarie. It would be nice if the same were available for the arduino mega. The more the better!

**Comment by evanshultz** [comment]
I assume the UNO symbols you're talking about these first two results here:
![image](https://user-images.githubusercontent.com/1936989/45180680-f0703700-b1d0-11e8-8e12-d6512578aa79.png)

Good idea to have one for the MEGA. And others. Create the symbols and submit a PR.

**Comment by antoniovazquezblanco** [comment]
@ajlaut we do not take symbol petitions in this bugtracker due to the high amount of work they generate. I fear this issue should be closed.

On the other hand we would be glad if you decided to contribute with a symbol for the Arduino MEGA component you are looking for.

Thank you!
