### ISSUE TITLE
AT90USB1286 schematic symbol missing pin 52, 53, 63

### ISSUE THREAD

**Issue by drylemon** [KiCad/kicad-symbols#902]
Hi, I'm fairly new to kicad, so forgive me if I am missing some sort of convention here. The schematic symbol for AT90USB1286 is missing pins 52, 53, and 63 (VCC, GND, GND respectively). This chip has multiple VCC and GND pins, is there a reason why only one appears on the schematic symbol?

If they need to be added, I can submit a PR.

**Comment by poeschlr** [comment]
They are there. Stacked on top of other VCC and GND pins like they should be.
![screenshot from 2018-09-09 10-30-39](https://user-images.githubusercontent.com/18327350/45262661-7f708f80-b41b-11e8-9d4c-e6905bf6e9db.png)
