### ISSUE TITLE
CP and CP1 symbol names

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#904]
From https://github.com/KiCad/kicad-symbols/pull/831. These two symbols are unclear as to their difference. Following the resistor paradigm in `Device.lib`, we should leave `CP` alone and rename `CP1` to `CP_US` when we have a chance to change symbol names.

**Comment by fauxpark** [comment]
I actually already covered this (among a bunch of other symbol renames in the Device lib) in #861 ;)
