### ISSUE TITLE
weekley release tags please

### ISSUE THREAD

**Issue by greyltc** [KiCad/kicad-symbols#911]
The `README.md` says that weekly releases can be found at https://kicad.github.io/symbols/

Can we get tags here that correspond to those weekly releases?

This would help me in packaging this for Arch Linux.

**Comment by poeschlr** [comment]
These are not really releases but snapshots. Adding tags every week will clutter the github pages for the library repos. If you want a sort of nightly release then use the master branch directly as is done for the source code of kicad.

**Comment by antoniovazquezblanco** [comment]
@greyltc Does this resolve your issues? Can this be closed?

**Comment by greyltc** [comment]
Is there a place I can go to see the history of the snapshots?
I don't really understand the cluttering actually, I thought tags just show up here: https://github.com/KiCad/kicad-symbols/tags

**Comment by evanshultz** [comment]
@poeschlr 
Ping.

**Comment by poeschlr** [comment]
tags sadly also show up on the release pages. Not in the same size but they are still shown.

See: https://github.com/KiCad/kicad.github.io/releases -> this is where you get your already compressed snapshots from.

**Comment by myfreescalewebpage** [comment]
@greyltc does it solves your issue ?

**Comment by greyltc** [comment]
Yes!

**Comment by myfreescalewebpage** [comment]
Thanks for the update!
