### ISSUE TITLE
Electrical type of `Vss` pin of `STM8S003F` series microcontroller symbol seems wrong!

### ISSUE THREAD

**Issue by mstfyghm** [KiCad/kicad-symbols#938]
Hi,
I've installed the following version of `KiCad` in my `ubuntu 18.04`:
`Version: 5.0.0-fee4fd1~66~ubuntu18.04.1, release build`
I used the `KiCad` default symbol libraries to place `STM8S003F3P` into schematic. After getting error in ERC check, I found that the electrical type of `Vss` pin of the symbol is set to `power output` , while it's set to `power input` in any other micro controllers.

**Comment by evanshultz** [comment]
Yup, seems wrong to me too. Would you mind submitting a PR to fix it?

**Comment by evanshultz** [comment]
This may be a good chance to try. Would you like to make your first PR to correct this issue?

**Comment by MostafaYaghmaei** [comment]
Yes, of course. I would like to submit my first PR. What should I do exactly?

**Comment by evanshultz** [comment]
You have two options:
1. Use the GitHub web client.
2. Make the changes on your local computer and commit them. Then submit a new PR to this repo of the changes. (This is the preferred option for several reasons.)

See https://help.github.com/articles/creating-a-pull-request-from-a-fork/ for method 1 or https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request for method 2. This is only the very basics and the first seemingly relevant link I found, so as you mentioned learning above so I'll leave it to you to Google for more information. Come back here if you need help, but please search for answers first so we can focus on KiCad-specific topics here and not Git topics.

Thanks!

**Comment by mstfyghm** [comment]
Thanks! :+1:

**Comment by evanshultz** [comment]
Fixed!
