### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/kicad-symbols#94]
There are now LOTS of libraries in a flat structure which makes them difficult to parse. Now that we are organizing by function, should we also split by directory (for large groups, at least). Each library must be uniquely named within the entire directory structure

* Sensor
   * Sensor_Pressure
   * Sensor_Temperature
   * Sensor_Motion
* MCU
   * MCU_Cypress
   * Microchip
      * PIC10
      * PIC12
      * PIC16
      * PIC18
      * PIC24
   * Texas
      * MSP430
      * Tiva
   * ST
      * STM32F3

**Comment by jkriege2** [comment]
Fine with me ... this should then als make transition to the 1-file-per-symbol approach with the new fileformat (somewhere in future ;-) easier ...

**Comment by poeschlr** [comment]
The sym lib table does support this, so why not.

**Comment by SchrodingersGat** [comment]
If we have time between completing the symbol transfer and release of v5, let's discuss then.

**Comment by evanshultz** [comment]
@poeschlr 
This seems completed. Right? If so, would you mind closing this issue?

**Comment by SchrodingersGat** [comment]
I'm happy to close this - perhaps can be implemented at a later stage but the library / community is not ready for another large sweeping change :)

**Comment by poeschlr** [comment]
I think the lib for v5 could have handled it. But as i plan on also releasing a backport for v4 this might have created problems. So i agree that we might want to postpone this for v6.

**Comment by Ratfink** [comment]
It doesn't seem like it should be hard to move files in to/out of directories and rename them in the process.  If you'd like, I could throw together a quick Python script to (un/)directory-ify the library for switching between v4 and v5 file layouts.  Then we might actually be able to do this change before v5.

Changing the file layout would have the little problem of breaking all the PRs we currently have open, though.  But that'll happen whenever we make this change, so it's not specifically an argument against doing it *now*.
