### ISSUE TITLE
Interface_Ethernet: S5.1 and S5.2 errors

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-symbols#970]
KLC Rules:
http://kicad-pcb.org/libraries/klc/S5.1/
http://kicad-pcb.org/libraries/klc/S5.2/

Splitting issue #28 I have found the following violations:

```
Checking symbol 'ENC424J600-ML':
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Specified footprint does not exist
     - Footprint file Package_DFN_QFN:QFN-44-1EP_8x8mm_P0.65mm was not found
```

**Comment by aewallin** [comment]
This seems fixed in the latest master (?)

> /kicad-library-utils/schlib$ ./checklib.py ../../kicad-symbols/Interface_Ethernet.lib -c ENC424J600-ML -vv
Checking symbol 'ENC424J600-ML' - No errors

**Comment by antoniovazquezblanco** [comment]
Thanks!
