### ISSUE TITLE
USB_B_Micro in Connector.lib has wrong electrical type on GND

### ISSUE THREAD

**Issue by r4ptor** [KiCad/kicad-symbols#989]
The symbol USB_B_Micro in Connector.lib has the GND pin labeled as power output.

Since it's a ground pin this should incorrect? It should be labeled as power input, as it is for the USB A, USB 3B connector and so on.

This can lead to problems with the ERC in the schematic.
In my case a design with a TI TPS60501 led to the error that two power outputs are connected. 

So in Connector.lib for the section of USB_B_Micro

`X GND 5 0 -400 100 U 50 50 1 1 w`

should be replaced with

`X GND 5 0 -400 100 U 50 50 1 1 W`

Same applies for USB_B.

USB_A, USB_OTG, USB_C_Receptacle, USB_C_Plug, USB3_B and USB3_A have to correct uppercase W label.

**Comment by antoniovazquezblanco** [comment]
Hi @r4ptor !

I believe the electrical type is right. Let me explain:

Imagine you have a host USB machine that defines a potential for GND. When you plug a cable into your USB B micro connector, then the host machine is trying to impose a potential in your GND pin, thus acting as "power source". If your circuit has another GND power source you need to use a fuse or a net tie to solve this problem. If you are aware of that problem you may also ignore that issue in the DRC.

I hope this clarifies a little bit the reasoning behind the scenes. Does this help you?

**Comment by r4ptor** [comment]
Hi @antoniovazquezblanco,

thanks for the explanation, makes sense for me. 

Closing the issue.

**Comment by antoniovazquezblanco** [comment]
Thank you @r4ptor!
